### ISSUE TITLE
v1.6.17集群同步出错

### ISSUE THREAD

**Issue by zhklcf** [aliyun/redis-shake#156]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x70d057]

goroutine 1499 [running]:
vendor/github.com/vinllen/redis-go-cluster.(*Cluster).RunBatch(0xc42d32a000, 0x0, 0xc42acd2b98, 0xc42b15a8c0, 0xc42b15a8c0, 0x0, 0x0)
        /home/zhuzhao.cx/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:123 +0x37
redis-shake/common.(*ClusterConn).Flush(0xc42caf29c0, 0x0, 0x0)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/cluster.go:64 +0x5a
redis-shake/common.flushAndCheckReply(0x978480, 0xc42caf29c0, 0x0)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:338 +0x35
redis-shake/common.restoreQuicklistEntry(0x978480, 0xc42caf29c0, 0xc428cb4420)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:385 +0x3d9
redis-shake/common.RestoreRdbEntry(0x978480, 0xc42caf29c0, 0xc428cb4420)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:761 +0x1986
redis-shake.(*dbSyncer).syncRDBFile.func1.1(0xc4254e7420, 0xc420106420, 0x6, 0x6, 0xc420146e53, 0x4, 0xc420146dc0, 0x0, 0x0, 0xc4296f1da0, ...)
        /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:447 +0x549
created by redis-shake.(*dbSyncer).syncRDBFile.func1
        /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:405 +0x131
```

**Comment by vinllen** [comment]
这个能稳定复现吗？开下debug看下报错的key，对应的value的长度多少？
报错这个key的value值能dump一下吗？

**Comment by zhklcf** [comment]
能稳定复现。日志输出太多了，但看不出是哪个key报错。这是最后输出的几行日志：
```
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COUNT_201877] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_PLAY_GAME_COUNT_340212] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_GAME_COMMENT_REPLY_COUNT_2993876] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_GAME_COMMENT_REPLY_COUNT_2993876] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_GAME_COMMENT_REPLY_COUNT_2993876] with params[[[85 83 69 82 95 71 65 77 69 95 67 79 77 77 69 78 84 95 82 69 80 76 89 95 67 79 85 78 84 95 50 57 57 51 56 55 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_244677] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_244677] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_244677] with params[[[85 83 69 82 95 85 78 82 69 65 68 95 83 89 83 84 69 77 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 50 52 52 54 55 55] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COUNT_1048777] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_GAME_COMMENT_REPLY_COUNT_308727] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_GAME_COMMENT_REPLY_COUNT_308727] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_SYSTEM_MESSAGE_COUNT_1870697] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_SYSTEM_MESSAGE_COUNT_1870697] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_SYSTEM_MESSAGE_COUNT_1870697] with params[[[85 83 69 82 95 83 89 83 84 69 77 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 49 56 55 48 54 57 55] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] cluster flush batch with size[100], return replies size[100]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_101099] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_SYSTEM_MESSAGE_COUNT_677456] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_PLAY_GAME_TOTAL_DURATION_20190619_2624548_5571] with value length[14]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_PLAY_GAME_COUNT_700675] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_PLAY_GAME_COUNT_700675] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_LIKE_MESSAGE_COUNT_2269834] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[TOPIC_THEME_REVISED_CLICK_COUNT_68631] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[TOPIC_THEME_REVISED_CLICK_COUNT_68631] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOKEN_ZSET_101316] ok
2019/09/04 10:14:42 [DEBUG] restore key[USER_PLAY_GAME_COUNT_700675] with params[[[85 83 69 82 95 80 76 65 89 95 71 65 77 69 95 67 79 85 78 84 95 55 48 48 54 55 53] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_GAME_COUNT_3280293] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_TOPIC_COUNT_1420491] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_REPLY_COUNT_192774] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COMMENT_COUNT_2197669] ok
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOPIC_COUNT_2610792] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_SYSTEM_MESSAGE_COUNT_1870697] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_REPLY_COUNT_2993876] ok
2019/09/04 10:14:42 [DEBUG] restore key[USER_TOPIC_COUNT_2610792] with params[[[85 83 69 82 95 84 79 80 73 67 95 67 79 85 78 84 95 50 54 49 48 55 57 50] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_1856962] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_LIKE_MESSAGE_COUNT_1856962] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_GAME_COMMENT_COUNT_1736990] with params[[[85 83 69 82 95 71 65 77 69 95 67 79 77 77 69 78 84 95 67 79 85 78 84 95 49 55 51 54 57 57 48] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_TOPIC_COUNT_1638743] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_TOPIC_COUNT_1638743] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_TOPIC_COUNT_1638743] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 84 79 80 73 67 95 67 79 85 78 84 95 49 54 51 56 55 52 51] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_UNREAD_REPLY_MEESAGE_COUNT_1041548] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_REPLY_COUNT_521504] ok
2019/09/04 10:14:42 [DEBUG] restore key[TOPIC_COMMENT_REPLY_COUNT_3583] with params[[[84 79 80 73 67 95 67 79 77 77 69 78 84 95 82 69 80 76 89 95 67 79 85 78 84 95 51 53 56 51] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_TOPIC_COUNT_3519235] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_SYSTEM_MESSAGE_COUNT_1562995] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_SYSTEM_MESSAGE_COUNT_924180] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[TOPIC_COMMENT_REPLY_COUNT_52295] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_1206072] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_GAME_COUNT_493248] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_UNREAD_REPLY_MEESAGE_COUNT_1484594] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COMMENT_COUNT_1909957] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_GAME_COMMENT_COUNT_2479141] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_GAME_COUNT_847300] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_646983] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_GAME_COMMENT_REPLY_COUNT_308727] with params[[[85 83 69 82 95 71 65 77 69 95 67 79 77 77 69 78 84 95 82 69 80 76 89 95 67 79 85 78 84 95 51 48 56 55 50 55] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_SYSTEM_MESSAGE_COUNT_2586321] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_SYSTEM_MESSAGE_COUNT_2586321] with params[[[85 83 69 82 95 83 89 83 84 69 77 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 50 53 56 54 51 50 49] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_PLAY_GAME_TOTAL_DURATION_20190619_2624548_5571] with value length[14]
2019/09/04 10:14:42 [DEBUG] restore key[USER_PLAY_GAME_TOTAL_DURATION_20190619_2624548_5571] with params[[[85 83 69 82 95 80 76 65 89 95 71 65 77 69 95 84 79 84 65 76 95 68 85 82 65 84 73 79 78 95 50 48 49 57 48 54 49 57 95 50 54 50 52 53 52 56 95 53 53 55 49] 0 [0 193 60 8 6 0 15 146 19 30 190 110 233 184]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_REPLY_COUNT_308727] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_LIKE_MESSAGE_COUNT_404196] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_LIKE_MESSAGE_COUNT_404196] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_REPLY_COUNT_3174889] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_TOPIC_COUNT_1794999] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_TOPIC_COUNT_1794999] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_TOPIC_COUNT_1794999] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 84 79 80 73 67 95 67 79 85 78 84 95 49 55 57 52 57 57 57] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COMMENT_COUNT_3320738] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_GAME_COUNT_1885473] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_GAME_COUNT_1885473] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[TOPIC_THEME_REVISED_CLICK_COUNT_68631] with params[[[84 79 80 73 67 95 84 72 69 77 69 95 82 69 86 73 83 69 68 95 67 76 73 67 75 95 67 79 85 78 84 95 54 56 54 51 49] 0 [0 192 37 6 0 26 166 60 89 254 183 163 41]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_GAME_COUNT_286816] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOPIC_COUNT_1420491] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_SYSTEM_MESSAGE_COUNT_1445139] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_TOKEN_ZSET_1933918] with value length[67]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_244677] ok
2019/09/04 10:14:42 [DEBUG] restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_1856962] with params[[[85 83 69 82 95 85 78 82 69 65 68 95 76 73 75 69 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 49 56 53 54 57 54 50] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_PLAY_GAME_TOTAL_DURATION_20190619_2624548_5571] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_REPLY_MESSAGE_COUNT_2109599] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_GAME_COUNT_2455371] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_GAME_COUNT_2455371] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_GAME_COUNT_2455371] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 71 65 77 69 95 67 79 85 78 84 95 50 52 53 53 51 55 49] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_LIKE_MESSAGE_COUNT_1967730] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_LIKE_MESSAGE_COUNT_1967730] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_LIKE_MESSAGE_COUNT_1967730] with params[[[85 83 69 82 95 76 73 75 69 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 49 57 54 55 55 51 48] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_TOPIC_COUNT_1794999] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_TOPIC_COMMENT_COUNT_821956] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_TOPIC_COUNT_3519235] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[TOPIC_THEME_REVISED_CLICK_COUNT_68631] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_1956376] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_1956376] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_TOPIC_COUNT_3519235] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 84 79 80 73 67 95 67 79 85 78 84 95 51 53 49 57 50 51 53] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_1956376] with params[[[85 83 69 82 95 85 78 82 69 65 68 95 83 89 83 84 69 77 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 49 57 53 54 51 55 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_1856962] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_PLAY_GAME_COUNT_700675] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_GAME_COUNT_2455371] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_TOPIC_COUNT_450041] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_TOPIC_COUNT_450041] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_TOPIC_COUNT_450041] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 84 79 80 73 67 95 67 79 85 78 84 95 52 53 48 48 52 49] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_LIKE_MESSAGE_COUNT_1967730] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_READ_USER_ID_SET_35935263593526] with value length[181]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_GAME_COMMENT_COUNT_2972827] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_PLAY_GAME_TOTAL_DURATION_20190706_3007490_6317] with value length[14]
2019/09/04 10:14:42 [DEBUG] cluster flush batch with size[85], return replies size[85]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_LIKE_MESSAGE_COUNT_1206072] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_GAME_COUNT_493248] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 71 65 77 69 95 67 79 85 78 84 95 52 57 51 50 52 56] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_LIKE_MESSAGE_COUNT_661148] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COUNT_2610792] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_GAME_COMMENT_COUNT_1736990] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_TOPIC_COUNT_1638743] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[AVG_MSG_USER_OFFICIAL_MESSAGE_ZSET_3097833] with value length[5890]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[TOPIC_COMMENT_REPLY_COUNT_3583] ok
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_GAME_COMMENT_COUNT_2479141] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_GAME_COUNT_847300] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 71 65 77 69 95 67 79 85 78 84 95 56 52 55 51 48 48] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_LIKE_MESSAGE_COUNT_646983] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_LIKE_MESSAGE_COUNT_404196] with params[[[85 83 69 82 95 76 73 75 69 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 52 48 52 49 57 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] restore key[USER_FAVORITE_GAME_COUNT_1885473] with params[[[85 83 69 82 95 70 65 86 79 82 73 84 69 95 71 65 77 69 95 67 79 85 78 84 95 49 56 56 53 52 55 51] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_SYSTEM_MESSAGE_COUNT_2586321] ok
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_GAME_COUNT_286816] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_TOPIC_COUNT_1420491] with params[[[85 83 69 82 95 84 79 80 73 67 95 67 79 85 78 84 95 49 52 50 48 52 57 49] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_SYSTEM_MESSAGE_COUNT_1445139] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOKEN_ZSET_1933918] with value length[67]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_PLAY_GAME_COUNT_206092] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_REPLY_MESSAGE_COUNT_2109599] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOPIC_COMMENT_COUNT_821956] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_TOPIC_COMMENT_COUNT_821956] with params[[[85 83 69 82 95 84 79 80 73 67 95 67 79 77 77 69 78 84 95 67 79 85 78 84 95 56 50 49 57 53 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_TOPIC_COUNT_1702887] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOPIC_COUNT_1702887] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_TOPIC_COUNT_1702887] with params[[[85 83 69 82 95 84 79 80 73 67 95 67 79 85 78 84 95 49 55 48 50 56 56 55] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_TOPIC_COMMENT_COUNT_1856942] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_TOPIC_COMMENT_COUNT_1856942] with value length[13]
2019/09/04 10:14:42 [DEBUG] cluster flush batch with size[100], return replies size[100]
2019/09/04 10:14:42 [DEBUG] restore key[USER_TOPIC_COMMENT_COUNT_1856942] with params[[[85 83 69 82 95 84 79 80 73 67 95 67 79 77 77 69 78 84 95 67 79 85 78 84 95 49 56 53 54 57 52 50] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_GAME_COMMENT_REPLY_COUNT_3482486] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_LIKE_MESSAGE_COUNT_404196] ok
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_GAME_COMMENT_REPLY_COUNT_3482486] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_GAME_COUNT_1885473] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_FAVORITE_TOPIC_COUNT_3096394] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_GAME_COMMENT_REPLY_COUNT_3482486] with params[[[85 83 69 82 95 71 65 77 69 95 67 79 77 77 69 78 84 95 82 69 80 76 89 95 67 79 85 78 84 95 51 52 56 50 52 56 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_FAVORITE_TOPIC_COUNT_3096394] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_READ_USER_ID_SET_35935263593526] with value length[181]
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_FAVORITE_GAME_COUNT_493248] ok
2019/09/04 10:14:42 [DEBUG] routine[0] restore key[USER_TOPIC_COUNT_1420491] ok
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_2577726] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] start restoring key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_2577726] with value length[13]
2019/09/04 10:14:42 [DEBUG] routine[0] try restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_1766008] with value length[13]
2019/09/04 10:14:42 [DEBUG] restore key[USER_UNREAD_SYSTEM_MESSAGE_COUNT_2577726] with params[[[85 83 69 82 95 85 78 82 69 65 68 95 83 89 83 84 69 77 95 77 69 83 83 65 71 69 95 67 79 85 78 84 95 50 53 55 55 55 50 54] 0 [0 192 0 6 0 14 173 207 248 13 5 63 155]]]
```

**Comment by vinllen** [comment]
把parallel参数调到1，最后一个报错的就是那个key

**Comment by zhklcf** [comment]
日志：
```
2019/09/04 13:10:49 [DEBUG] routine[0] try restore key[SCENE_CV_USE_RECORD_52542] with value length[420]
2019/09/04 13:10:49 [DEBUG] routine[0] start restoring key[SCENE_CV_USE_RECORD_52542] with value length[420]
2019/09/04 13:10:49 [DEBUG] cluster flush batch with size[100], return replies size[100]
2019/09/04 13:10:49 [DEBUG] cluster flush batch with size[85], return replies size[85]
2019/09/04 13:10:49 [DEBUG] cluster flush batch with size[100], return replies size[100]
2019/09/04 13:10:49 [DEBUG] cluster flush batch with size[85], return replies size[85]
2019/09/04 13:10:49 [DEBUG] cluster flush batch with size[100], return replies size[100]
```
dump value:

DUMP SCENE_CV_USE_RECORD_52542
```
"\x0e\x03\xc3@\x91_\xd7\x04\xd7\x1f\x00\x00\xaa \x03\x1b\xb9\x00\x00*{\"cvId\":52542,\"source\":1\xc0\n@\x1b\x0630599},\xe0\xff+\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xa5\a\x01}\xff\xc3@\x91_\xd7\x04\xd7\x1f\x00\x00\xaa \x03\x1b\xb9\x00\x00*{\"cvId\":52542,\"source\":1\xc0\n@\x1b\x0630599},\xe0\xff+\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xa5\a\x01}\xff\xc3@gQ;\x04;\x11\x00\x00\x0e \x03\x1bd\x00\x00*{\"cvId\":52542,\"source\":1\xc0\n@\x1b\x0630599},\xe0\xff+\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1\xff\a\xe1y\a\x01}\xff\t\x00\xec\xbf\x82\x8f\xe0\x8e2\xa6"
```

**Comment by vinllen** [comment]
感谢反馈，这个问题是驱动没有处理输入为空的情况，导致panic了，我一起修一下发个v1.6.18版本。也感谢反馈了不少问题，我把你加到contributor list里面。

**Comment by vinllen** [comment]
v1.6.18版本已发布

**Comment by zhklcf** [comment]
ok~👌

**Comment by stillerrr** [comment]
请问 这个问题老版本有没有规避方法

**Comment by suxb201** [comment]
> 请问 这个问题老版本有没有规避方法

没有，自己改代码或者升版本
