### ISSUE TITLE
5.0.5集群到集群间同步异常 报错：[PANIC] dbSyncer[11] Event:ErrorReply Id:redis-shake Command: [unknown] Error: invalid response

### ISSUE THREAD

**Issue by xuhualin** [aliyun/redis-shake#184]
2019/11/11 16:44:08 [DEBUG] cluster flush batch with size[1], return replies size[1]
2019/11/11 16:44:08 [DEBUG] receive reply-id[2290486]: [1], error:[<nil>]
2019/11/11 16:44:08 [DEBUG] cluster flush batch with size[1], return replies size[1]
2019/11/11 16:44:08 [DEBUG] receive reply-id[1209355]: [21], error:[<nil>]
2019/11/11 16:44:08 [DEBUG] dbSyncer[11] send command[1209356]: [lpop [doki:show:live_show_comments_list_9315734579]]
2019/11/11 16:44:08 [DEBUG] receive reply-id[1209356]: [<nil>], error:[invalid response]
2019/11/11 16:44:08 [PANIC] dbSyncer[11] Event:ErrorReply	Id:redis-shake	Command: [unknown]	Error: invalid response
[stack]:
    0   /usr/local/src/RedisShake/src/redis-shake/sync.go:552
            redis-shake.(*dbSyncer).syncCommand.func2
        ... ...
异常log如上
注释：两端集群版本均为5.0.5，同步方式为sync

**Comment by vinllen** [comment]
进一步报错信息：
```
2019/11/15 17:43:49 [INFO] dbSyncer[3] sync:  +forwardCommands=105    +filterCommands=0      +writeBytes=42024
2019/11/15 17:43:49 [INFO] dbSyncer[11] total = 324.303MB -    324.303MB [100%]  entry=387118
2019/11/15 17:43:49 [INFO] dbSyncer[6] sync:  +forwardCommands=143    +filterCommands=0      +writeBytes=140862
2019/11/15 17:43:49 [INFO] dbSyncer[11] total = 324.303MB -    324.303MB [100%]  entry=387203
2019/11/15 17:43:49 [INFO] dbSyncer[11] sync rdb done
2019/11/15 17:43:49 [INFO] dbSyncer[11] Event:IncrSyncStart  Id:redis-shake
2019/11/15 17:43:49 [WARN] dbSyncer[11] GetFakeSlaveOffset not enable when psync == false
2019/11/15 17:43:49 [WARN] available channel size[4096] less than current returned batch size[4097]
2019/11/15 17:43:49 [INFO] dbSyncer[5] sync:  +forwardCommands=150    +filterCommands=0      +writeBytes=21706
2019/11/15 17:43:49 [INFO] dbSyncer[1] sync:  +forwardCommands=105    +filterCommands=0      +writeBytes=27317
2019/11/15 17:43:49 [WARN] available channel size[4096] less than current returned batch size[4097]
2019/11/15 17:43:49 [PANIC] decode redis resp failed
[error]: unexpected EOF
    5   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:146
            pkg/redis.(*Decoder).decodeBulkBytes
    4   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:84
            pkg/redis.(*Decoder).decodeResp
    3   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:166
            pkg/redis.(*Decoder).decodeArray
    2   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:88
            pkg/redis.(*Decoder).decodeResp
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:36
            pkg/redis.MustDecodeOpt
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:596
            redis-shake.(*dbSyncer).syncCommand.func3
        ... ...
[stack]:
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/pkg/redis/decoder.go:38
            pkg/redis.MustDecodeOpt
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:596
            redis-shake.(*dbSyncer).syncCommand.func3
        ... ...
```

**Comment by vinllen** [comment]
修改send count为4095仍然报错：
```
panic: runtime error: index out of range

goroutine 3356598 [running]:
vendor/github.com/vinllen/redis-go-cluster.(*redisConn).readReply(0xc4290c5d60, 0xbf6d02155a4b40e8, 0x29cbbba3948, 0xbd0720, 0x0)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/node.go:465 +0xb29
vendor/github.com/vinllen/redis-go-cluster.(*redisConn).receive(0xc4290c5d60, 0x856c80, 0xc42c6abf90, 0x0, 0x0)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/node.go:223 +0xae
vendor/github.com/vinllen/redis-go-cluster.doBatch(0xc42945e038)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:143 +0x180
created by vendor/github.com/vinllen/redis-go-cluster.(*Cluster).RunBatch
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:102 +0x8c
2019/11/19 16:09:03 [INFO] input password is empty, skip auth address[10.0.110.152:6378] with type[].
2019/11/19 16:09:03 [INFO] input password is empty, skip auth address[10.0.110.159:6388] with type[auth].
panic: runtime error: index out of range

goroutine 14524971 [running]:
vendor/github.com/vinllen/redis-go-cluster.(*redisConn).readReply(0xc4260e9720, 0xbf6d0dc58c5f507d, 0x9e6ca2e6858, 0xbd0720, 0x0)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/node.go:465 +0xb29
vendor/github.com/vinllen/redis-go-cluster.(*redisConn).receive(0xc4260e9720, 0x0, 0x0, 0xc42c1a5780, 0x1)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/node.go:223 +0xae
vendor/github.com/vinllen/redis-go-cluster.doBatch(0xc428e8b7c0)
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:143 +0x180
created by vendor/github.com/vinllen/redis-go-cluster.(*Cluster).RunBatch
  /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:102 +0x8c
```

**Comment by vinllen** [comment]
问题已修复，1.6.22版本
