### ISSUE TITLE
迁移redis5.0.8 cluster to cluster 增量同步报错

### ISSUE THREAD

**Issue by jiaxuabc123** [aliyun/redis-shake#273]
我用redis-shakev2.0.0-20200422 版本 对redis5.0.8 cluster to cluster 进行迁移操作，同时旧的cluster 进行持续写入，在全量同步结束之后，redis-shark在进行增量同步就会报错，如果刚开始不持续写入，redis-shake 的增量同步日志正常显示，一旦开启写入，增量同步就会报错，程序退出。
`# cat redis-shake.conf`
conf.version = 1
id = redis-shake
log.file = /var/log/redis-shake.log
log.level = debug
pid_path = /var/run/redis-shake.pid
system_profile = 9310
http_profile = 9320
parallel = 2
source.type = cluster
source.address = 192.168.19.151:6379;192.168.19.152:6379;192.168.19.153:6379
source.password_raw = password
source.auth_type = auth
source.tls_enable = false
target.type = cluster
target.address = 192.168.19.154:6379;192.168.19.155:6379;192.168.19.156:6379
target.password_raw =password
target.auth_type = auth
target.db = -1
target.tls_enable = false
rewrite = true
sender.size = 104857600
sender.count = 4095
sender.delay_channel_size = 65535
keep_alive = 0

`#bin/redis-shake.linux  -conf=conf/redis-shake.conf -type=sync`
panic: runtime error: index out of range [2] with length 1
goroutine 94 [running]:
vendor/github.com/vinllen/redis-go-cluster.(*Cluster).ChooseNodeWithCmd(0xc01ad80000, 0xc01c60c116, 0x6, 0xc01acc2170, 0x1, 0x1, 0x5f, 0xc000dc09b8, 0x40dfb6)
	/var/cloud/RedisShake/src/vendor/github.com/vinllen/redis-go-cluster/cluster.go:193 +0x119b
vendor/github.com/vinllen/redis-go-cluster.(*Batch).Put(0xc000066680, 0xc01c60c116, 0x6, 0xc01acc2170, 0x1, 0x1, 0xa2f6e0, 0xc000066cc0)
	/var/cloud/RedisShake/src/vendor/github.com/vinllen/redis-go-cluster/batch.go:54 +0x87
redis-shake/common.(*ClusterConn).Send(0xc01acf1200, 0xc01c60c116, 0x6, 0xc01acc2170, 0x1, 0x1, 0x0, 0x1)
	/var/cloud/RedisShake/src/redis-shake/common/cluster.go:59 +0x75
redis-shake/dbSync.(*DbSyncer).sendTargetCommand.func1()
	/var/cloud/RedisShake/src/redis-shake/dbSync/syncIncrease.go:303 +0x2a0
redis-shake/dbSync.(*DbSyncer).sendTargetCommand(0xc0000a4800, 0xa38380, 0xc01acf1200)
	/var/cloud/RedisShake/src/redis-shake/dbSync/syncIncrease.go:405 +0x820
created by redis-shake/dbSync.(*DbSyncer).syncCommand
	/var/cloud/RedisShake/src/redis-shake/dbSync/syncIncrease.go:43 +0x2bb

日志信息：
`# tail -f /var/log/redis-shake.log`
2020/04/30 17:37:09 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/04/30 17:37:09 [INFO] DbSyncer[1] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/04/30 17:37:10 [INFO] DbSyncer[0] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/04/30 17:37:10 [INFO] DbSyncer[2] sync:  +forwardCommands=0      +filterCommands=0      +writeBytes=0
2020/04/30 17:37:10 [DEBUG] DbSyncer[0] command[select] with barrier status[add barrier] and flush status[1]
2020/04/30 17:37:10 [DEBUG] DbSyncer[0] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[0] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[1] command[select] with barrier status[add barrier] and flush status[1]
2020/04/30 17:37:10 [DEBUG] DbSyncer[1] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[2] command[select] with barrier status[add barrier] and flush status[1]
2020/04/30 17:37:10 [DEBUG] DbSyncer[2] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[0] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[0] command[set] with barrier status[] and flush status[0]
2020/04/30 17:37:10 [DEBUG] DbSyncer[1] command[set] with barrier status[] and flush status[0]

**Comment by jiaxuabc123** [comment]
已解决，把 target.db = -1  设置为 0 就可以了
