### ISSUE TITLE
how to use redis-3.0 --redis-shake-linux-amd64?

### ISSUE THREAD

**Issue by Azure-why** [aliyun/redis-shake#472]
not found any document

**Comment by suxb201** [comment]
- https://github.com/alibaba/RedisShake#usage
- https://github.com/alibaba/RedisShake/blob/v3/redis-shake.toml

Could these links solve your problem?

**Comment by Azure-why** [comment]
thanks,but i'm not compiling with source code.
I'm using links https://github.com/alibaba/RedisShake/releases --> [redis-shake-v3.0.0.tar.gz]
how to use the tool? or i can only compile with source code.

**Comment by suxb201** [comment]
redis-shake-v3.0.0.tar.gz is compiled from the source code.
1. modify the `redis-shake.toml`, replace address with yours.
2. `./redis-shake-linux-amd64 redis-shake.toml`

**Comment by Azure-why** [comment]
I did that but i got an error;Attached is the error log.
-----------------------
[redis@ycnsz01vl0023 redisshake]$ ./redis-shake-linux-amd64 redis-shake.toml 
2022-08-12 18:25:29 INF GOOS: linux, GOARCH: amd64
2022-08-12 18:25:29 INF Ncpu: 3, GOMAXPROCS: 3
2022-08-12 18:25:29 INF pid: 29879
2022-08-12 18:25:29 INF pprof_port: 0
2022-08-12 18:25:29 INF No lua file specified, will not filter any cmd.
2022-08-12 18:25:29 INF auth successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisClusterWriter load cluster nodes. line=d3bc19a60bfa152e4d6b217c8e57aa9d399b4c20 xx.xx.xx.xx:xxxx@1xxxx master - 0 1660299927108 2 connected 5461-10922
2022-08-12 18:25:29 INF auth successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisWriter connected to redis successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisClusterWriter load cluster nodes. line=9d2e693d619c311ab5dad4df5509962a30925fe0 xx.xx.xx.xx:xxxx@1xxxx master - 0 1660299929111 3 connected 10923-16383
2022-08-12 18:25:29 INF auth successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisWriter connected to redis successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisClusterWriter load cluster nodes. line=6823ee9643595aebca8b112b6df2894be974af03 xx.xx.xx.xx:xxxx@1xxxx myself,master - 0 1660299926000 1 connected 0-5460
2022-08-12 18:25:29 INF auth successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisWriter connected to redis successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF redisClusterWriter connected to redis cluster successful. addresses=[xx.xx.xx.xx:xxxx xx.xx.xx.xx:xxxx xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF auth successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF psyncReader connected to redis successful. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 WRN remove file. filename=[838203423.aof]
2022-08-12 18:25:29 WRN remove file. filename=[dump.rdb]
2022-08-12 18:25:29 INF start save RDB. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:29 INF send [replconf listening-port 10007]
2022-08-12 18:25:29 INF send [PSYNC ? -1]
2022-08-12 18:25:29 INF receive [FULLRESYNC 781577cf37aa456c0431b9a6f789ba3beb56bf42 838203765]
2022-08-12 18:25:29 INF source db is doing bgsave. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:30 INF source db bgsave finished. timeUsed=[0.78]s, address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:30 INF received rdb length. length=[44746657]
2022-08-12 18:25:30 INF create dump.rdb file. filename_path=[dump.rdb]
2022-08-12 18:25:30 INF save RDB finished. address=[xx.xx.xx.xx:xxxx], total_bytes=[44746657]
2022-08-12 18:25:30 INF start send RDB. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:30 INF RDB version: 8
2022-08-12 18:25:30 INF RDB AUX fields. key=[redis-ver], value=[4.0.14]
2022-08-12 18:25:30 INF RDB AUX fields. key=[redis-bits], value=[64]
2022-08-12 18:25:30 INF RDB AUX fields. key=[ctime], value=[1660299929]
2022-08-12 18:25:30 INF RDB AUX fields. key=[used-mem], value=[156197336]
2022-08-12 18:25:30 INF RDB repl-stream-db: 0
2022-08-12 18:25:30 INF start save AOF. address=[xx.xx.xx.xx:xxxx]
2022-08-12 18:25:30 INF RDB AUX fields. key=[repl-id], value=[781577cf37aa456c0431b9a6f789ba3beb56bf42]
2022-08-12 18:25:30 INF RDB AUX fields. key=[repl-offset], value=[838203765]
2022-08-12 18:25:30 INF RDB AUX fields. key=[aof-preamble], value=[0]
2022-08-12 18:25:30 INF RDB resize db. db_size=[60086], expire_size=[60085]
2022-08-12 18:25:30 INF AOFWriter open file. filename=[838203765.aof]
2022-08-12 18:25:30 PNC redisWriter received error. error=[ERR syntax error], argv=[restore TASK:T1270597963723280385 1660892564295 �A�BH{"xxxxxxxx@paddS!uleT!(-996B
                                                                                                                             urgencyDegre@+     ordinary"}*Kplace absttl], slots=[16007], reply=[<nil>]

goroutine 8 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc0000e0a00, 0x269)
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc0001440c0, 0xc0000e0a00, 0x269)
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0001440c0, 0x82d5f2, 0x45, 0xc000060f88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x82d5f2, 0x45, 0xc000060f88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000146270)
        github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x267
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:32 +0x199

-----------------------

**Comment by Azure-why** [comment]
What should i do ?😢😢😢

**Comment by suxb201** [comment]
1. What is the type of key `TASK:T1270597963723280385`?
2. What are the Redis versions of the source and destination?
