### ISSUE TITLE
[CRASH] ERR Bad data format

### ISSUE THREAD

**Issue by takakawa** [aliyun/redis-shake#482]
**Crash report**

```
���receive�����`$���W�F� replace idletime 1889264], slots=[2150], reply=[<nil>]
panic: redisWriter received error. error=[ERR Bad data format], argv=[restore xxxxxxxxx 0 �;@J�send_like
dis@
���receive�����`$���W�F� replace idletime 1889264], slots=[2150], reply=[<nil>]

goroutine 8 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc00025a000, 0xed)
	github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc0000fc660, 0xc00025a000, 0xed)
	github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0000fc660, 0x82d5f2, 0x45, 0xc00024ff88, 0x4, 0x4)
	github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x82d5f2, 0x45, 0xc00024ff88, 0x4, 0x4)
	github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000098270)
	github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x267
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
	github.com/alibaba/RedisShake/internal/writer/redis.go:32 +0x199

```

源： redis_version:7.0.4
目标：redis_version:5.0.4

**Comment by suxb201** [comment]
7.0 有新增编码格式，5.0 不兼容。建议升级目标库版本到 7.0
