### ISSUE TITLE
使用AWS Redis做为源时，报这样的错误是为啥？

### ISSUE THREAD

**Issue by yjiu1990** [aliyun/redis-shake#506]
**问题描述**

这里描述你的问题。

redis-shake 的日志：
```
2022-09-28 13:28:39 INF syncing rdb. percent=[99.50]%, allowOps=[15484.20], disallowOps=[0.00], entryId=[14034792], unansweredBytesCount=[140089]bytes, rdbFileSize=[0.955]G, rdbSendSize=[0.951]G
2022-09-28 13:28:43 INF send RDB finished. address=[aws-sgb-zgame-redis.mf5wo3.ng.0001.apse1.cache.amazonaws.com:6379], repl-stream-db=[0]
2022-09-28 13:28:44 INF syncing aof. allowOps=[13456.20], disallowOps=[0.00], entryId=[14103098], unansweredBytesCount=[0]bytes, diff=[94303535402], aofReceivedOffset=[94303535402], aofAppliedOffset=[0]
2022-09-28 13:28:44 INF AOFReader open file. aof_filename=[94294902360.aof]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341989666]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341990669]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341991670]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341992675]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341993678]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341994681]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341995683]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341996685]
2022-09-28 13:28:44 WRN unknown command. argv=[REPLCONF TIMESTAMP 1664341997688]
2022-09-28 13:28:44 PNC redisWriter received error. error=[ERR Unrecognized REPLCONF option: TIMESTAMP], argv=[REPLCONF TIMESTAMP 1664341989666], slots=[], reply=[<nil>]
panic: redisWriter received error. error=[ERR Unrecognized REPLCONF option: TIMESTAMP], argv=[REPLCONF TIMESTAMP 1664341989666], slots=[], reply=[<nil>]

goroutine 21 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc00021c000, 0x91)
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc000214000, 0xc00021c000, 0x91)
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000214000, 0x82d5f2, 0x45, 0xc000102f88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x82d5f2, 0x45, 0xc000102f88, 0x4, 0x4)
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001938c0)
        github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x267
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:32 +0x199
```

---

**源端 Redis**
版本：AWS Redis 5.x

---

**目的端 Redis**
版本：阿里云5.x

**Comment by suxb201** [comment]
看起来 AWS 会发一些非标命令，建议使用 Lua 过滤掉 replconf：https://github.com/alibaba/RedisShake/wiki/%E4%BD%BF%E7%94%A8-filters-%E5%81%9A%E6%95%B0%E6%8D%AE%E6%B8%85%E6%B4%97

**Comment by suxb201** [comment]
https://github.com/alibaba/RedisShake/blob/v3/filters/aws.lua
