### ISSUE TITLE
同步完数据后异常退出，panic: EOF

### ISSUE THREAD

**Issue by fotan123456** [aliyun/redis-shake#523]
2022-11-07 17:28:07 INF syncing aof. allowOps=[0.20], disallowOps=[0.00], entryId=[627], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2276831111], aofAppliedOffset=[2276831111]
2022-11-07 17:28:08 PNC EOF
2022-11-07 17:28:08 INF AOFWriter close file. filename=[2276830943.aof], filesize=[168]
panic: EOF

goroutine 38 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1(0xc002660cb0, 0x3)
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x4f
github.com/rs/zerolog.(*Event).msg(0xc0000960c0, 0xc002660cb0, 0x3)
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x30c
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0000960c0, 0x816869, 0x3, 0x0, 0x0, 0x0)
        github.com/alibaba/RedisShake/internal/log/func.go:71 +0x85
github.com/alibaba/RedisShake/internal/log.Panicf(0x816869, 0x3, 0x0, 0x0, 0x0)
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x6d
github.com/alibaba/RedisShake/internal/log.PanicError(0x88fb60, 0xc000048070)
        github.com/alibaba/RedisShake/internal/log/func.go:31 +0x5a
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc0001ac000, 0x88f900, 0xc000096060)
        github.com/alibaba/RedisShake/internal/reader/psync.go:199 +0x1e5
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
        github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0x9f

**Comment by fotan123456** [comment]
补充说明，redis-shake版本3.0.0 ，redis 版本：source、target都是5.0

**Comment by suxb201** [comment]
@fotan123456 3.0.0 太旧了，中间很多 bugfix，试一下 3.1.7

**Comment by matrixoom** [comment]
你好，我们用的3.1.10这个版本也报的这个错误。
2023-05-24 06:59:52 INF syncing aof. allowOps=[111.60], disallowOps=[0.00], entryId=[1239113], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[104], aofReceivedOffset=[2134528929512], aofAppliedOffset=[2134528929408]
2023-05-24 06:59:53 PNC EOF
2023-05-24 06:59:53 INF AOFWriter close file. filename=[2134523603347.aof], filesize=[5356119]
panic: EOF

goroutine 8 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0008a3032, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000076960, {0xc0008a3032, 0x3})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc000076960, {0x79f1e9, 0xc0000100d8}, {0x0, 0x1, 0xc00003ff08})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x79f1e9, 0x3}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81b8a0, 0xc000020080})
        github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc000088050, {0x81b640, 0xc000076660})
        github.com/alibaba/RedisShake/internal/reader/psync.go:202 +0x166
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
        github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef

看了下常见问题，说是可能是源端的缓存太小了，实际看了下，还挺大的
config get client-output-buffer-limit
1) "client-output-buffer-limit"
2) "normal 0 0 0 slave 4347483648 4347483647 60 pubsub 33554432 8388608 60"

请问这个错误还有其他原因吗，怎么解决，谢谢
