### ISSUE TITLE
使用sync模式进行数据迁移，任务中断并出现 "redis: invalid reply: \"\\r\\n\""

### ISSUE THREAD

**Issue by q999666** [aliyun/redis-shake#525]
**问题描述**

使用sync模式进行数据迁移，任务中断并出现 "redis: invalid reply: \"\\r\\n\""，有时会出现 can't parse "wEIP"

redis-shake 的日志：
```
{"level":"info","time":"2022-11-10T15:56:35+08:00","message":"syncing rdb. percent=[98.85]%, allowOps=[4.40], disallowOps=[0.00], entryId=[3920], InQueueEntriesCount=[1015], unansweredBytesCount=[0]bytes, rdbFileSize=[0.166]G, rdbSendSize=[0.164]G"}
{"level":"info","time":"2022-11-10T15:56:40+08:00","message":"syncing rdb. percent=[98.85]%, allowOps=[0.00], disallowOps=[0.00], entryId=[3920], InQueueEntriesCount=[1015], unansweredBytesCount=[0]bytes, rdbFileSize=[0.166]G, rdbSendSize=[0.164]G"}
{"level":"info","time":"2022-11-10T15:56:45+08:00","message":"syncing rdb. percent=[99.31]%, allowOps=[114.20], disallowOps=[0.00], entryId=[4491], InQueueEntriesCount=[893], unansweredBytesCount=[412855]bytes, rdbFileSize=[0.166]G, rdbSendSize=[0.165]G"}
{"level":"info","time":"2022-11-10T15:56:46+08:00","message":"LUA script: [        local sKey = KEYS[1];\n        local nKey = KEYS[2];\n        local now = tonumber(ARGV[1]);\n        local rate = tonumber(ARGV[2]);\n        local max = tonumber(ARGV[3]);\n        local default = tonumber(ARGV[4]);\n        \n        local sNum = redis.call('get', sKey);\n        if((not sNum) or sNum == nil)\n        then\n            sNum = 0\n        end\n        \n        sNum = tonumber(sNum);\n        \n        local nNum = redis.call('get', nKey);\n        if((not nNum) or nNum == nil)\n        then\n            nNum = now\n            sNum = default\n        end\n        \n        nNum = tonumber(nNum);\n        \n        local newPermits = 0;\n        if(now > nNum)\n        then\n              newPermits = (now-nNum)*rate+sNum;\n              sNum = math.min(newPermits, max)\n        end\n        \n        local isPermited = 0;\n        if(sNum > 0)\n        then\n            sNum = sNum -1;\n            isPermited = 1;\n        end\n        \n        redis.call('set', sKey, sNum);\n        redis.call('set', nKey, now);\n        redis.call('expire', sKey, 60);\n        redis.call('expire', nKey, 60);\n        \n        return isPermited;]"}
{"level":"info","time":"2022-11-10T15:56:46+08:00","message":"send RDB finished. address=[x.x.x.x:6379], repl-stream-db=[0]"}
{"level":"info","time":"2022-11-10T15:56:47+08:00","message":"AOFReader open file. aof_filename=[37658398.aof]"}
{"level":"info","time":"2022-11-10T15:56:50+08:00","message":"syncing aof. allowOps=[1848.40], disallowOps=[0.00], entryId=[13733], InQueueEntriesCount=[880], unansweredBytesCount=[338438]bytes, diff=[1481672], aofReceivedOffset=[41912982], aofAppliedOffset=[40431310]"}
{"level":"panic","time":"2022-11-10T15:56:53+08:00","message":"redis: invalid reply: \"\\r\\n\""}
{"level":"info","time":"2022-11-10T15:56:53+08:00","message":"AOFReader close file. aof_filename=[37658398.aof]"}
```

---

**源端 Redis**
版本：4.0.9，自建
日志：
```
23330:C 10 Nov 15:55:24.491 * RDB: 2 MB of memory used by copy-on-write
11459:M 10 Nov 15:55:24.513 * Background saving terminated with success
11459:M 10 Nov 15:56:53.448 # Connection with slave 192.168.0.3:10007 lost.
11459:M 10 Nov 15:57:10.651 * 10000 changes in 60 seconds. Saving...
11459:M 10 Nov 15:57:10.668 * Background saving started by pid 23333
```

---

**目的端 Redis**
版本：7.0.5，自建
日志：
```
4876:M 10 Nov 2022 15:56:02.405 * Background AOF rewrite terminated with success
4876:M 10 Nov 2022 15:56:02.405 * Successfully renamed the temporary AOF base file temp-rewriteaof-bg-10775.aof into appendonly.aof.8.base.rdb
4876:M 10 Nov 2022 15:56:02.416 * Removing the history file appendonly.aof.7.incr.aof in the background
4876:M 10 Nov 2022 15:56:02.416 * Removing the history file appendonly.aof.7.base.rdb in the background
4876:M 10 Nov 2022 15:56:02.425 * Background AOF rewrite finished successfully
4876:M 10 Nov 2022 15:56:31.430 * 10000 changes in 60 seconds. Saving...
4876:M 10 Nov 2022 15:56:31.440 * Background saving started by pid 10777
10777:C 10 Nov 2022 15:56:34.031 * DB saved on disk
10777:C 10 Nov 2022 15:56:34.039 * Fork CoW for RDB: current 8 MB, peak 8 MB, average 6 MB
4876:M 10 Nov 2022 15:56:34.065 * Background saving terminated with success
4876:M 10 Nov 2022 15:57:35.043 * 10000 changes in 60 seconds. Saving...
4876:M 10 Nov 2022 15:57:35.053 * Background saving started by pid 10781
```

**Comment by q999666** [comment]
2022-11-10 17:02:13 PNC redis: can't parse "176"
2022-11-10 17:02:13 INF AOFReader close file. aof_filename=[1.aof]
panic: redis: can't parse "176"

goroutine 9 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0079fb9b0, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc005e62060, {0xc0079fb9b0, 0x18})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc005e62060, {0xc0079fb998, 0x5c9ca5}, {0x0, 0x81b8a0, 0xc0079fb998})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc0079fb998, 0x18}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81b8a0, 0xc009f74c80})
        github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.ArrayString({0x0, 0x0}, {0x81b8a0, 0xc009f74c80})
        github.com/alibaba/RedisShake/internal/client/reply.go:7 +0x46
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendAOF(0xc000066640, 0xc00012e020)
        github.com/alibaba/RedisShake/internal/reader/psync.go:223 +0x22f
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
        github.com/alibaba/RedisShake/internal/reader/psync.go:51 +0x114
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
        github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f

**Comment by suxb201** [comment]
没找到问题，稳定复现吗？Redis 有没有魔改过？或者试试过滤掉 lua。

**Comment by suxb201** [comment]
@q999666 请问怎么解决的？

**Comment by q999666** [comment]
没解决，可能是源Redis 的数据有点问题，影响不大
