### ISSUE TITLE
redis集群之间同步异常

### ISSUE THREAD

**Issue by wangchao665739** [aliyun/redis-shake#532]
同步一段时间后，redis-shake自动挂掉
{"level":"panic","time":"2022-11-24T16:46:49+08:00","message":"EOF"}
{"level":"info","time":"2022-11-24T16:46:49+08:00","message":"AOFWriter close file. filename=[1385795846.aof], filesize=[21401536]"}
这是最后的日志。不知道什么原因造成。

**Comment by suxb201** [comment]
日志发全些看看

**Comment by wangchao665739** [comment]
{"level":"info","time":"2022-11-22T16:36:15+08:00","message":"syncing aof. allowOps=[2.60], disallowOps=[0.00], entryId=[3093], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007507789], aofAppliedOffset=[2007507789]"}
{"level":"info","time":"2022-11-22T16:36:20+08:00","message":"syncing aof. allowOps=[1.60], disallowOps=[0.00], entryId=[3101], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007508882], aofAppliedOffset=[2007508882]"}
{"level":"info","time":"2022-11-22T16:36:25+08:00","message":"syncing aof. allowOps=[1.00], disallowOps=[0.00], entryId=[3106], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007509443], aofAppliedOffset=[2007509443]"}
{"level":"info","time":"2022-11-22T16:36:30+08:00","message":"syncing aof. allowOps=[1.60], disallowOps=[0.20], entryId=[3115], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[179], aofReceivedOffset=[2007510716], aofAppliedOffset=[2007510537]"}
{"level":"info","time":"2022-11-22T16:36:35+08:00","message":"syncing aof. allowOps=[1.80], disallowOps=[0.00], entryId=[3124], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007511824], aofAppliedOffset=[2007511824]"}
{"level":"info","time":"2022-11-22T16:36:40+08:00","message":"syncing aof. allowOps=[0.80], disallowOps=[0.00], entryId=[3128], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007512371], aofAppliedOffset=[2007512371]"}
{"level":"info","time":"2022-11-22T16:36:45+08:00","message":"syncing aof. allowOps=[1.80], disallowOps=[0.20], entryId=[3138], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007513653], aofAppliedOffset=[2007513653]"}
{"level":"info","time":"2022-11-22T16:36:50+08:00","message":"syncing aof. allowOps=[4.80], disallowOps=[0.00], entryId=[3162], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007516932], aofAppliedOffset=[2007516932]"}
{"level":"info","time":"2022-11-22T16:36:55+08:00","message":"syncing aof. allowOps=[1.00], disallowOps=[0.00], entryId=[3167], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[2007517493], aofAppliedOffset=[2007517493]"}
{"level":"panic","time":"2022-11-22T16:36:58+08:00","message":"EOF"}
{"level":"info","time":"2022-11-22T16:36:58+08:00","message":"AOFWriter close file. filename=[2007412161.aof], filesize=[105511]"}

**Comment by wangchao665739** [comment]
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"auth successful. address=[xxx:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"redisWriter connected to redis successful. address=[10.2.67.209:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"redisClusterWriter connected to redis cluster successful. addresses=[10.2.67.201:6379 10.2.67.171:6379 10.2.67.209:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"auth successful. address=[xxx:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"psyncReader connected to redis successful. address=[10.38.53.42:6379]"}
{"level":"warn","time":"2022-11-22T16:30:30+08:00","message":"remove file. filename=[1400979180.aof]"}
{"level":"warn","time":"2022-11-22T16:30:30+08:00","message":"remove file. filename=[dump.rdb]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"start save RDB. address=[xxx:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"send [replconf listening-port 10007]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"send [PSYNC ? -1]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"receive [FULLRESYNC a5fdb24494b3b5153ca42606bb379b932eea8140 2007412161]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"source db is doing bgsave. address=[xxx:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"source db bgsave finished. timeUsed=[0.06]s, address=[10.38.53.42:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"received rdb length. length=[431848]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"create dump.rdb file. filename_path=[dump.rdb]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"save RDB finished. address=[xxx:6379], total_bytes=[431848]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"start send RDB. address=[xxx:6379]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB version: 9"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB AUX fields. key=[redis-ver], value=[6.2.6]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB AUX fields. key=[redis-bits], value=[64]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB AUX fields. key=[ctime], value=[1669105830]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB AUX fields. key=[used-mem], value=[8505760]"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB repl-stream-db: 0"}
{"level":"info","time":"2022-11-22T16:30:30+08:00","message":"RDB AUX fields. key=[repl-id], value=[a5fdb24494b3b5153ca42606bb379b932eea8140]"}

**Comment by suxb201** [comment]
@wangchao665739 日志文件中没有保留栈，不确定 EOF 是哪个函数抛出来的，请问你有终端的 log 吗？终端应该有报错时的栈。

**Comment by wangchao665739** [comment]
edOffset=[1707064777]
2022-11-30 11:44:47 INF syncing aof. allowOps=[12.80], disallowOps=[0.00], entryId=[517132], InQueueEntriesCount=[0], unansweredBytesCount=[12033]bytes, diff=[12033], aofReceivedOffset=[1707085026], aofAppliedOffset=[1707072993]
2022-11-30 11:44:52 INF syncing aof. allowOps=[11.40], disallowOps=[0.00], entryId=[517189], InQueueEntriesCount=[0], unansweredBytesCount=[1275]bytes, diff=[23546], aofReceivedOffset=[1707092697], aofAppliedOffset=[1707069151]
2022-11-30 11:44:57 INF syncing aof. allowOps=[10.40], disallowOps=[0.00], entryId=[517241], InQueueEntriesCount=[0], unansweredBytesCount=[12032]bytes, diff=[12032], aofReceivedOffset=[1707099807], aofAppliedOffset=[1707087775]
2022-11-30 11:45:00 PNC EOF
2022-11-30 11:45:00 INF AOFWriter close file. filename=[1638510320.aof], filesize=[68595517]
panic: EOF

goroutine 38 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0003f56b8, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00039dc80, {0xc0003f56b8, 0x3})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc00039dc80, {0x79f1e9, 0xc000010068}, {0x0, 0x0, 0xc000040f08})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x79f1e9, 0x3}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81b8a0, 0xc000090060})
        github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc0000680a0, {0x81b640, 0xc00005e420})
        github.com/alibaba/RedisShake/internal/reader/psync.go:202 +0x166
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
        github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef

**Comment by suxb201** [comment]
这个是源端把连接断掉了，请提供下同时刻源端 Redis 的日志。一般是源端缓冲区满了，需要调整缓冲区大小。
