### ISSUE TITLE
从redis cluster向另一个redis cluster时传输异常

### ISSUE THREAD

**Issue by NikolaNddTesla** [aliyun/redis-shake#534]
传输时出现换库,然后报一下错误
PNC redisWriter received error. error=[MOVED 9506 10.0.141.76:2001], argv=[

**Comment by suxb201** [comment]
换库指的是主备切换吗？确实目前如果出现主备切换或者任何路由表的变化都会导致 shake 报错。

**Comment by vauns** [comment]
在源端cluster和目标端cluster的slot分布不一致时，通过restore rdb方式时会出现这种错误

**Comment by suxb201** [comment]
@vauns 不会有问题

**Comment by vauns** [comment]
详细描述下我遇这个异常时的具体场景。
1、当将源端 cluster 的低槽位的那个节点（比如0-5460）的rdb放到目标端 cluster 的高槽位的节点（只要源端和目标端的槽位分布不一致就会有问题），使用 restore 模式就会报如下错误，因为rdb中的key根据crc算法算出的slot不在本节点，重定向到对应槽位节点，这里说下sync模式测试是没问题的。
 ```shell
 [root@localhost redis-shake-30001]# ./redis-shake restore.toml
2023-07-24 02:04:54 INF GOOS: linux, GOARCH: amd64
2023-07-24 02:04:54 INF Ncpu: 3, GOMAXPROCS: 3
2023-07-24 02:04:54 INF pid: 12990
2023-07-24 02:04:54 INF pprof_port: 0
2023-07-24 02:04:54 INF No lua file specified, will not filter any cmd.
2023-07-24 02:04:54 INF no password. address=[127.0.0.1:30001]
2023-07-24 02:04:54 INF redisWriter connected to redis successful. address=[127.0.0.1:30001]
2023-07-24 02:04:54 INF NewRDBReader: path=[/root/dump-30003.rdb]
2023-07-24 02:04:54 INF NewRDBReader: absolute path=[/root/dump-30003.rdb]
2023-07-24 02:04:54 INF start send RDB. path=[/root/dump-30003.rdb]
2023-07-24 02:04:54 INF RDB version: 6
2023-07-24 02:04:54 INF goroutine 35 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2790, 0x45}, {0xc000102f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001269c0)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:80 +0x369  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:36 +0x19c  [
@��z-07-24 02:04:54 PNC redisWriter received error. error=[MOVED 12709 127.0.0.1:30003], argv=[restore KIdH1b9ayz 0
age�6address (92243 Cindy Plaza
Lake Timothy, DC 17889*name
random_string                Jared Smith
KIdH1b9ayz
          emailgcobb@yahoo.com����Ǔv�M replace], slots=[12709], reply=[<nil>]
@��zc: redisWriter received error. error=[MOVED 12709 127.0.0.1:30003], argv=[restore KIdH1b9ayz 0
age�6address (92243 Cindy Plaza
Lake Timothy, DC 17889*name
random_string                Jared Smith
KIdH1b9ayz
          emailgcobb@yahoo.com����Ǔv�M replace], slots=[12709], reply=[<nil>]

goroutine 35 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0000be000, 0x0})
        github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000098060, {0xc0000be000, 0x11c})
        github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc000098060, {0x7b2790, 0x21d}, {0xc000093f78, 0x79a446, 0x3})
        github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2790, 0x45}, {0xc000093f78, 0x4, 0x4})
        github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001269c0)
        github.com/alibaba/RedisShake/internal/writer/redis.go:80 +0x369
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:36 +0x19c
[root@localhost redis-shake-30001]#
```
2、当源端cluster集群3主3从，目标端cluster节点6主6从，节点slot分布肯定也不一致，所以也会报如上的错，测试也如期报错。

**Comment by suxb201** [comment]
1. 那肯定不行的
2. 使用 sync 模式吗？没问题的

**Comment by vauns** [comment]
1和2 都是为了表述源cluster的某个节点的 rdb 的 key 的 slot 分布和目标cluster节点的 slot 分布不一致。
1和2 使用 sync 模式是正常的，没有问题。
1和2 使用 restore 模式都会报这个错，我自己明白报错是正常的。

只是为了阐述我遇到过的和问题描述一致错误的特殊场景。

**Comment by git1e** [comment]
我也遇到了相同的问题，redis6.0.2 三主三从迁移redis6.0.2 三主三从,sync和scan模式都不行，redis-shake-v4.0.2
