### ISSUE TITLE
Rdb finished,tcp broken pipe

### ISSUE THREAD

**Issue by lidaling** [aliyun/redis-shake#535]
**问题描述**

redis4.0迁移数据向redis5.0 部分shard rdb 文件写完时 tcp broken pipe。

--日志--

```log
2022-11-30 11:36:26 PNC write tcp 172.20.122.103:59626->55.50.3.21:6381: write: broken pipe
panic: write tcp 172.20.122.103:59626->55.50.3.21:6381: write: broken pipe

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00231a050, 0x0})
github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0000920c0, {0xc00231a050, 0x43})
github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0000920c0, {0xc00231a000, 0xc000124288}, {0x0, 0x2f, 0xc000016390})
github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00231a000, 0x43}, {0x0, 0x0, 0x0})
github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81bc20, 0xc00015e410})
github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).SendBytes(0xc000024100, {0xc002314000, 0xc000038800, 0xc0001ea870})
github.com/alibaba/RedisShake/internal/client/redis.go:92 +0x3a
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).Write(0xc0001e74c0, 0xc00012f540)
github.com/alibaba/RedisShake/internal/writer/redis.go:54 +0x12d
github.com/alibaba/RedisShake/internal/writer.(*RedisClusterWriter).Write(0xc00021a000, 0xc00012f540)
github.com/alibaba/RedisShake/internal/writer/redis_cluster.go:114 +0x16e
main.main()
github.com/alibaba/RedisShake/cmd/redis-shake/main.go:109 +0x7fa
```

---

**源端 Redis**
版本：4.0.1，自建

---

**目的端 Redis**
版本：5.02，是集群,云厂商

**Comment by suxb201** [comment]
麻烦发下完整日志

**Comment by lidaling** [comment]
> 麻烦发下完整日志

tcp boken pipe .进程退出。启动时重新 syncing rdb 
```log
2022-11-30 11:36:26 PNC write tcp 172.20.122.103:59626->55.50.3.21:6381: write: broken pipe
panic: write tcp 172.20.122.103:59626->55.50.3.21:6381: write: broken pipe

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00231a050, 0x0})
github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0000920c0, {0xc00231a050, 0x43})
github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0000920c0, {0xc00231a000, 0xc000124288}, {0x0, 0x2f, 0xc000016390})
github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00231a000, 0x43}, {0x0, 0x0, 0x0})
github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81bc20, 0xc00015e410})
github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).SendBytes(0xc000024100, {0xc002314000, 0xc000038800, 0xc0001ea870})
github.com/alibaba/RedisShake/internal/client/redis.go:92 +0x3a
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).Write(0xc0001e74c0, 0xc00012f540)
github.com/alibaba/RedisShake/internal/writer/redis.go:54 +0x12d
github.com/alibaba/RedisShake/internal/writer.(*RedisClusterWriter).Write(0xc00021a000, 0xc00012f540)
github.com/alibaba/RedisShake/internal/writer/redis_cluster.go:114 +0x16e
main.main()
github.com/alibaba/RedisShake/cmd/redis-shake/main.go:109 +0x7fa
```


这是另外一种 错误，未报tcp broken ,但结果是一样的，进程退出。启动时重新 syncing rdb 
```log 
2022-11-30 10:11:32 INF send RDB finished. address=[99.47.134.116:6379], repl-stream-db=[0]
2022-11-30 10:11:32 INF syncing aof. allowOps=[3085.40], disallowOps=[0.00], entryId=[858233], InQueueEntriesCount=[861], unansweredBytesCount=[48682]bytes, diff=[4270184477], aofReceivedOffset=[4270184477], aofAppliedOffset=[0]
2022-11-30 10:11:33 INF AOFReader open file. aof_filename=[4270178672.aof]
2022-11-30 10:11:33 PNC redisWriter received error. error=[EOF], argv=[PING], slots=[], reply=[<nil>]
panic: redisWriter received error. error=[EOF], argv=[PING], slots=[], reply=[<nil>]

goroutine 4 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000292000, 0x0})
github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0002a8c60, {0xc000292000, 0x4d})
github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0002a8c60, {0x7b742a, 0x40c0ca}, {0xc000031f78, 0x745ea0, 0x407001})
github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b742a, 0x45}, {0xc000031f78, 0x4, 0x4})
github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc00016f640)
github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c

```

**Comment by suxb201** [comment]
目的端的问题吧，哪家云，能看日志吗？
把这些值改小些试试：
```toml
# pipeline
pipeline_count_limit = 1024

# Client query buffers accumulate new commands. They are limited to a fixed
# amount by default. This amount is normally 1gb.
target_redis_client_max_querybuf_len = 1024_000_000

# In the Redis protocol, bulk requests, that are, elements representing single
# strings, are normally limited to 512 mb.
target_redis_proto_max_bulk_len = 512_000_000
```

**Comment by lidaling** [comment]
> 

好的。测试后给你反馈。
内部自建云，应该基于微软那一套的吧

另外请问怎么指定fullsync id呢，目的是想在进程退出后重启时 能续传rdb

**Comment by lidaling** [comment]
> 日志



> 

内部自建云，应该基于微软那一套的吧

**Comment by lidaling** [comment]
> 目的端的问题吧，哪家云，能看日志吗？ 把这些值改小些试试：
> 
> ```toml
> # pipeline
> pipeline_count_limit = 1024
> 
> # Client query buffers accumulate new commands. They are limited to a fixed
> # amount by default. This amount is normally 1gb.
> target_redis_client_max_querybuf_len = 1024_000_000
> 
> # In the Redis protocol, bulk requests, that are, elements representing single
> # strings, are normally limited to 512 mb.
> target_redis_proto_max_bulk_len = 512_000_000
> ```



> 把这些值改小些试试：

目前来看 执行节点在云上，改小参数后未报错
执行节点在云下的话，还是有tcp broken pipe 问题。
感谢

**Comment by lidaling** [comment]
> > 
> 
> 好的。测试后给你反馈。 内部自建云，应该基于微软那一套的吧
> 
> 另外请问怎么指定fullsync id呢，目的是想在进程退出后重启时 能续传rdb

参数 改小后进行测试，如果 数据量大的话 长时间 30分钟后，仍然有 `write tcp ip->ip: write : broken pipe` 问题，进程退出，重启后 进行fullresync 。 

请问有什么解决办法 没？多谢

**Comment by lidaling** [comment]
> 目的端的问题吧，哪家云，能看日志吗？ 把这些值改小些试试：
> 
> ```toml
> # pipeline
> pipeline_count_limit = 1024
> 
> # Client query buffers accumulate new commands. They are limited to a fixed
> # amount by default. This amount is normally 1gb.
> target_redis_client_max_querybuf_len = 1024_000_000
> 
> # In the Redis protocol, bulk requests, that are, elements representing single
> # strings, are normally limited to 512 mb.
> target_redis_proto_max_bulk_len = 512_000_000
> ```

参数 改小后进行测试，如果 数据量大的话 长时间 30分钟后，仍然有 write tcp ip->ip: write : broken pipe 问题，进程退出，重启后 fullresync 。

请问有什么解决办法 没？多谢

**Comment by suxb201** [comment]
看一下目的端日志吧，要确认是哪个节点吧 tcp 连接关闭了。

**Comment by lidaling** [comment]
> 看一下目的端日志吧，要确认是哪个节点吧 tcp 连接关闭了。

问题找到了，是目标服务那边网络问题。其会主动闲置5分钟左右的连接。而现在我们测试的环境 是跨城，网络比较慢，saveRdb 后可能 会遇到 目标机器连接被关闭，就会出现这个问题。
现在改了下源码 把NewRedisClusterWriter 置后，目前测下来再没有出现 tcp broken问题。

所以 建议 把目标机器的连接 在需要时进行连接 ，或一直保持redis ping 操作。避免闲置连接被关闭。

**Comment by suxb201** [comment]
@lidaling 明白了，同步阶段源端会向 shake 发送 ping。aof 同步阶段 shake 会把 ping 命令转发给目的端 Redis 的，所以没问题。但是 saveRDB 阶段，shake 是不会转发 ping 命令到目的端的。

**Comment by lidaling** [comment]
> @lidaling 明白了，同步阶段源端会向 shake 发送 ping。aof 同步阶段 shake 会把 ping 命令转发给目的端 Redis 的，所以没问题。但是 saveRDB 阶段，shake 是不会转发 ping 命令到目的端的。

savefRDB阶段 可以也进行转发ping操作吗？

**Comment by suxb201** [comment]
应该是这里超时的
```go
	log.Infof("source db is doing bgsave. address=[%s]", r.address)
	statistics.Metrics.IsDoingBgsave = true

	timeStart := time.Now()
	// format: \n\n\n$<length>\r\n<rdb>
	for true {
		// \n\n\n$
		b, err := r.rd.ReadByte()
		if err != nil {
			log.PanicError(err)
		}
		if b == '\n' {
			continue
		}
		if b != '$' {
			log.Panicf("invalid rdb format. address=[%s], b=[%s]", r.address, string(b))
		}
		break
	}
	statistics.Metrics.IsDoingBgsave = false
```

这里会一直收到来自源端的 \n，shake 最好向目的端发送 ping 来保活。

不过你的情况也是特殊，一般网络环境下不会断连的，你应该是经过 LB、Proxy 之类的组件了吧？

**Comment by lidaling** [comment]
> 你应该是经过 LB、Proxy 之类的组件了吧？

对的 目标集群 前边有个SLB 组件
