### ISSUE TITLE
无法连接 redis

### ISSUE THREAD

**Issue by timandy** [aliyun/redis-shake#541]
redis-shake 日志
```
./redis-shake sync.toml 
2022-12-08 11:04:11 INF GOOS: linux, GOARCH: amd64
2022-12-08 11:04:11 INF Ncpu: 4, GOMAXPROCS: 4
2022-12-08 11:04:11 INF pid: 972403
2022-12-08 11:04:11 INF pprof_port: 0
2022-12-08 11:04:11 INF No lua file specified, will not filter any cmd.
2022-12-08 11:04:11 PNC ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
panic: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00006e100, 0x0})
	github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00005e120, {0xc00006e100, 0x7c})
	github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc00005e120, {0xc00006e000, 0xc00005c040}, {0x0, 0xc000157c20, 0x669d9e})
	github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00006e000, 0x7c}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81c3a0, 0xc000048030})
	github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc0000b25a0, {0xc000157d20, 0xc000010010, 0x79f345})
	github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50
github.com/alibaba/RedisShake/internal/client.NewRedisClient({0xc0000ac108, 0x13}, {0x0, 0x0}, {0xc0000b4f10, 0xc}, 0x0)
	github.com/alibaba/RedisShake/internal/client/redis.go:46 +0x636
github.com/alibaba/RedisShake/internal/writer.NewRedisWriter({0xc0000ac108, 0x13}, {0x0, 0x0}, {0xc0000b4f10, 0xc}, 0x10)
	github.com/alibaba/RedisShake/internal/writer/redis.go:30 +0x87
main.main()
	github.com/alibaba/RedisShake/cmd/redis-shake/main.go:73 +0x425

```

 
---

**源端 Redis**
版本：7.0.5 自建 standalone 默认用户 有密码

---

**目的端 Redis**
版本：7.0.5 自建 standalone   默认用户 有密码
![image](https://user-images.githubusercontent.com/3809541/206346617-b6697b0f-720a-4950-8fc5-1186e7a33f7d.png)

**Comment by suxb201** [comment]
自己用 redis-cli 连接，然后试试 auth password 可以吗？

**Comment by timandy** [comment]
@suxb201 sorry 部署脚本用错了, 目标库没设置密码
