### ISSUE TITLE
redisshake  eof error

### ISSUE THREAD

**Issue by wavelet123** [aliyun/redis-shake#563]
**问题描述**

redis shake同步失败，错误日志如下：
redis-shake 的日志：
```
panic: redisWriter received error. error=[EOF], argv=[REPLCONF GETACK *], slots=[], reply=[<nil>]

goroutine 9 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00001e120, 0x0})
        github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0002b3560, {0xc00001e120, 0x5a})
        github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
        github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0002b3560, {0x7b742a, 0x40c0ca}, {0xc000089f78, 0x745ea0, 0x407001})
        github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b742a, 0x45}, {0xc000089f78, 0x4, 0x4})
        github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001182c0)
        github.com/alibaba/RedisShake/internal/writer/redis.go:74 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
        github.com/alibaba/RedisShake/internal/writer/redis.go:34 +0x18f```

{"level":"panic","time":"2023-02-23T16:08:43+03:00","message":"redisWriter received error. error=[EOF], argv=[EVAL local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val) 1 PlayerLogin_idx_158407869_1 158407869], slots=[2171], reply=[<nil>]"}
{"level":"panic","time":"2023-02-23T16:08:43+03:00","message":"redisWriter received error. error=[EOF], argv=[REPLCONF GETACK *], slots=[], reply=[<nil>]"}

换成从主库同步，报错信息如下:
{"level":"panic","time":"2023-02-23T16:16:55+03:00","message":"redisWriter received error. error=[EOF], argv=[REPLCONF GETACK *], slots=[], reply=[<nil>]"}
---

**源端 Redis**
版本：版本号，自建还是云厂商？
redis 4.0.12 自建redis cluster
日志：
```
9259:C 23 Feb 20:45:16.845 * RDB: 103 MB of memory used by copy-on-write
32461:S 23 Feb 20:45:16.920 * Background saving terminated with success
32461:S 23 Feb 20:45:18.383 * Synchronization with slave 192.168.xxx.9:10007 succeeded
32461:S 23 Feb 20:49:16.001 # Connection with slave 192.168.xxx.9:10007 lost.```

---

**目的端 Redis**
版本：版本号，是否是集群？自建还是云厂商？
redis 6.2.6 自建集群
日志：
```
575897:M 22 Feb 2023 16:24:50.546 * Synchronization with replica 192.168.xxx.3:6691 succeeded
575897:M 22 Feb 2023 16:28:51.608 # CONFIG REWRITE executed with success.
```

**Comment by wavelet123** [comment]
{"level":"panic","time":"2023-02-23T16:08:43+03:00","message":"redisWriter received error. error=[EOF], argv=[EVAL local val = 0 if redis.call('GET', KEYS[1]) == ARGV[1] then val = redis.call('DEL', KEYS[1]) end return tostring(val) 1 PlayerLogin_idx_158407869_1 158407869], slots=[2171], reply=[<nil>]"}

不知道是不是和这段lua 脚本有关，是分布式锁使用的

**Comment by wavelet123** [comment]
2023-02-24 13:34:03 PNC redisWriter received error. error=[EOF], argv=[script load 
                redis.call('HMSET', KEYS[1], 'absexp', ARGV[1], 'sldexp', ARGV[2], 'data', ARGV[4])
                if ARGV[3] ~= '-1' then
                  redis.call('EXPIRE', KEYS[1], ARGV[3])
                end
                return 1], slots=[], reply=[<nil>]
panic: write tcp 192.168.xxx.9:54302->192.168.xxx.44:6699: write: broken pipe

我用了 filter中的skip_scripts.lua,还是报错

**Comment by wavelet123** [comment]
过滤replconf命令后问题解决
