### ISSUE TITLE
使用Scan模式同步数据，当源Redis是集群模式时，报错 PNC ERR SELECT is not allowed in cluster mode

### ISSUE THREAD

**Issue by code66889** [aliyun/redis-shake#566]
**使用Scan模式同步数据，当源Redis是集群模式时，报错**

报错 PNC ERR SELECT is not allowed in cluster mode

redis-shake 的日志：
```
[root@ip-172-31-45-244 ~]# ./redis-shake scan.toml
2023-02-28 03:39:53 INF GOOS: linux, GOARCH: amd64
2023-02-28 03:39:53 INF Ncpu: 0, GOMAXPROCS: 1
2023-02-28 03:39:53 INF pid: 3781
2023-02-28 03:39:53 INF pprof_port: 0
2023-02-28 03:39:53 INF No lua file specified, will not filter any cmd.
2023-02-28 03:39:53 INF no password. address=[127.0.0.1:6379]
2023-02-28 03:39:53 INF redisWriter connected to redis successful. address=[127.0.0.1:6379]
2023-02-28 03:39:53 INF no password. address=[172.31.17.33:6379]
2023-02-28 03:39:53 INF no password. address=[172.31.17.33:6379]
2023-02-28 03:39:53 INF scanReader connected to redis successful. address=[172.31.17.33:6379]
2023-02-28 03:39:53 PNC ERR SELECT is not allowed in cluster mode
panic: ERR SELECT is not allowed in cluster mode

goroutine 10 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00017ad50, 0x0})
	github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0000544e0, {0xc00017ad50, 0x29})
	github.com/rs/zerolog@v1.27.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.27.0/event.go:108
github.com/alibaba/RedisShake/internal/log.logFinally(0xc0000544e0, {0xc00017ad20, 0xc000052b40}, {0x0, 0xc000043ed0, 0x669d9e})
	github.com/alibaba/RedisShake/internal/log/func.go:77 +0x53
github.com/alibaba/RedisShake/internal/log.Panicf({0xc00017ad20, 0x29}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:27 +0x57
github.com/alibaba/RedisShake/internal/log.PanicError({0x81c3a0, 0xc000174fc0})
	github.com/alibaba/RedisShake/internal/log/func.go:31 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc000012660, {0xc000043f98, 0x2, 0x4e8668})
	github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50
github.com/alibaba/RedisShake/internal/reader.(*scanReader).scan(0xc000052b00)
	github.com/alibaba/RedisShake/internal/reader/scan_reader.go:52 +0xb5
created by github.com/alibaba/RedisShake/internal/reader.(*scanReader).StartRead
	github.com/alibaba/RedisShake/internal/reader/scan_reader.go:43 +0xc7
```

---

**源端 Redis**
```
源端： AWS MemoryDB 【redis 6.2】
```

---

**目的端 Redis**
```
启动的开源Redis，版本 6.2.7
```

**Comment by suxb201** [comment]
感谢反馈，已经修复。试一试新版本：https://github.com/alibaba/RedisShake/releases/tag/v3.1.9
