### ISSUE TITLE
长时间同步报错 panic: write 0.aof: file too large

### ISSUE THREAD

**Issue by xiaolin8** [aliyun/redis-shake#568]
**问题描述**

RedisShake 长时间运行同步报错：

redis-shake 的日志：
```
2023-03-06 13:59:56 INF syncing aof. allowOps=[53.80], disallowOps=[0.00], entryId=[88483], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[847], aofReceivedOffset=[509733889], aofAppliedOffset=[509733042]
2023-03-06 14:00:01 INF syncing aof. allowOps=[60.40], disallowOps=[0.00], entryId=[88785], InQueueEntriesCount=[0], unansweredBytesCount=[11518]bytes, diff=[11029], aofReceivedOffset=[511467348], aofAppliedOffset=[511456319]
2023-03-06 14:00:02 INF goroutine 51 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc000214020, 0x1b}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x1411ae0, 0xc0001e8630})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/reader/rotate.(*AOFWriter).Write(0xc00014bf78, {0xc0000b2000, 0x4000, 0x4000})]<-github.com/alibaba/RedisShake/internal/reader/rotate/aof_writer.go:39 +0x45  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc00009c000, {0x14115c0, 0xc0001100c0})]<-github.com/alibaba/RedisShake/internal/reader/psync.go:206 +0x12b  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1]<-github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef  [
2023-03-06 14:00:02 PNC write 0.aof: file too large
2023-03-06 14:00:02 INF AOFWriter close file. filename=[0.aof], filesize=[511985435]
panic: write 0.aof: file too large

goroutine 51 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000214120, 0x0})
        github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0001a4720, {0xc000214120, 0x1b})
        github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc0001a4720, {0xc000214020, 0x394}, {0x0, 0x1395f04, 0x3})
        github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc000214020, 0x1b}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x1411ae0, 0xc0001e8630})
        github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/reader/rotate.(*AOFWriter).Write(0xc000259f78, {0xc0000b2000, 0x4000, 0x4000})
        github.com/alibaba/RedisShake/internal/reader/rotate/aof_writer.go:39 +0x45
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc00009c000, {0x14115c0, 0xc0001100c0})
        github.com/alibaba/RedisShake/internal/reader/psync.go:206 +0x12b
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
        github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef
```

---

**源端 Redis**
版本：5.0.10，自建 单机 standalone
日志：
```
25:M 06 Mar 2023 13:48:50.997 * Background saving terminated with success
25:M 06 Mar 2023 13:51:11.743 * Starting automatic rewriting of AOF on 73146% growth
25:M 06 Mar 2023 13:51:11.745 * Background append only file rewriting started by pid 1259261
25:M 06 Mar 2023 13:51:11.775 * AOF rewrite child asks to stop sending diffs.
1259261:C 06 Mar 2023 13:51:11.775 * Parent agreed to stop sending diffs. Finalizing AOF...
1259261:C 06 Mar 2023 13:51:11.775 * Concatenating 0.00 MB of AOF diff received from parent.
1259261:C 06 Mar 2023 13:51:11.775 * SYNC append only file rewrite performed
1259261:C 06 Mar 2023 13:51:11.775 * AOF rewrite: 10 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:51:11.845 * Background AOF rewrite terminated with success
25:M 06 Mar 2023 13:51:11.845 * Residual parent diff successfully flushed to the rewritten AOF (0.02 MB)
25:M 06 Mar 2023 13:51:11.845 * Background AOF rewrite finished successfully
25:M 06 Mar 2023 13:51:48.507 * 10000 changes in 60 seconds. Saving...
25:M 06 Mar 2023 13:51:48.509 * Background saving started by pid 1259311
1259311:C 06 Mar 2023 13:51:48.519 * DB saved on disk
1259311:C 06 Mar 2023 13:51:48.519 * RDB: 12 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:51:48.610 * Background saving terminated with success
25:M 06 Mar 2023 13:54:34.383 * Starting automatic rewriting of AOF on 83640% growth
25:M 06 Mar 2023 13:54:34.385 * Background append only file rewriting started by pid 1259512
25:M 06 Mar 2023 13:54:34.414 * AOF rewrite child asks to stop sending diffs.
1259512:C 06 Mar 2023 13:54:34.415 * Parent agreed to stop sending diffs. Finalizing AOF...
1259512:C 06 Mar 2023 13:54:34.415 * Concatenating 0.00 MB of AOF diff received from parent.
1259512:C 06 Mar 2023 13:54:34.415 * SYNC append only file rewrite performed
1259512:C 06 Mar 2023 13:54:34.415 * AOF rewrite: 10 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:54:34.486 * Background AOF rewrite terminated with success
25:M 06 Mar 2023 13:54:34.486 * Residual parent diff successfully flushed to the rewritten AOF (0.02 MB)
25:M 06 Mar 2023 13:54:34.486 * Background AOF rewrite finished successfully
25:M 06 Mar 2023 13:54:40.396 * 10000 changes in 60 seconds. Saving...
25:M 06 Mar 2023 13:54:40.398 * Background saving started by pid 1259519
1259519:C 06 Mar 2023 13:54:40.412 * DB saved on disk
1259519:C 06 Mar 2023 13:54:40.412 * RDB: 11 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:54:40.498 * Background saving terminated with success
25:M 06 Mar 2023 13:57:32.848 * 10000 changes in 60 seconds. Saving...
25:M 06 Mar 2023 13:57:32.850 * Background saving started by pid 1259732
1259732:C 06 Mar 2023 13:57:32.860 * DB saved on disk
1259732:C 06 Mar 2023 13:57:32.861 * RDB: 11 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:57:32.951 * Background saving terminated with success
25:M 06 Mar 2023 13:57:56.094 * Starting automatic rewriting of AOF on 83573% growth
25:M 06 Mar 2023 13:57:56.096 * Background append only file rewriting started by pid 1259757
25:M 06 Mar 2023 13:57:56.127 * AOF rewrite child asks to stop sending diffs.
1259757:C 06 Mar 2023 13:57:56.127 * Parent agreed to stop sending diffs. Finalizing AOF...
1259757:C 06 Mar 2023 13:57:56.127 * Concatenating 0.00 MB of AOF diff received from parent.
1259757:C 06 Mar 2023 13:57:56.128 * SYNC append only file rewrite performed
1259757:C 06 Mar 2023 13:57:56.128 * AOF rewrite: 11 MB of memory used by copy-on-write
25:M 06 Mar 2023 13:57:56.196 * Background AOF rewrite terminated with success
25:M 06 Mar 2023 13:57:56.196 * Residual parent diff successfully flushed to the rewritten AOF (0.03 MB)
25:M 06 Mar 2023 13:57:56.197 * Background AOF rewrite finished successfully
25:M 06 Mar 2023 14:02:33.055 * 10 changes in 300 seconds. Saving...
25:M 06 Mar 2023 14:02:33.057 * Background saving started by pid 1260098
1260098:C 06 Mar 2023 14:02:33.066 * DB saved on disk
1260098:C 06 Mar 2023 14:02:33.067 * RDB: 8 MB of memory used by copy-on-write
25:M 06 Mar 2023 14:02:33.158 * Background saving terminated with success
```

---

**目的端 Redis**
版本：5.0.10，自建 单机 standalone
```bash
➜  redis-shake-darwin-amd64 ls -lh data
total 1016456
-rw-r--r--  1 xiaolin  staff   488M Mar  6 14:13 0.aof
-rw-r--r--  1 xiaolin  staff    56K Mar  6 13:34 dump.rdb
-rw-r--r--  1 xiaolin  staff    89K Mar  6 14:00 redis-shake.log
-rw-r--r--  1 xiaolin  staff   123K Mar  6 14:13 redis-shake2.log
```

**Comment by suxb201** [comment]
怀疑是你的文件系统限制了最大文件大小，你可以试试能不能手动创建 1G 大小的文件。
