### ISSUE TITLE
redis 5 一主二从三哨兵写入redis6.2  一主二从三哨兵 日志报错 PNC EOF，而且源redis 变成目标redis的从节点

### ISSUE THREAD

**Issue by yuqun20230302** [aliyun/redis-shake#569]
**问题描述**

这里描述你的问题。

redis-shake 的日志：
```
[hadoop@dsx001 redis-shake3]$ ./redis-shake sync.toml 
2023-03-06 11:50:03 INF GOOS: linux, GOARCH: amd64
2023-03-06 11:50:03 INF Ncpu: 4, GOMAXPROCS: 4
2023-03-06 11:50:03 INF pid: 190887
2023-03-06 11:50:03 INF pprof_port: 0
2023-03-06 11:50:03 INF No lua file specified, will not filter any cmd.
2023-03-06 11:50:03 INF auth successful. address=[172.16.13.116:26385]
2023-03-06 11:50:03 INF redisWriter connected to redis successful. address=[172.16.13.116:26385]
2023-03-06 11:50:03 INF auth successful. address=[172.16.13.116:6385]
2023-03-06 11:50:03 INF psyncReader connected to redis successful. address=[172.16.13.116:6385]
2023-03-06 11:50:03 INF start save RDB. address=[172.16.13.116:6385]
2023-03-06 11:50:03 INF send [replconf listening-port 10007]
2023-03-06 11:50:03 INF send [PSYNC ? -1]
2023-03-06 11:50:03 INF receive [FULLRESYNC f120c62558b07bc1d3826f67b9a141b3c3ace6f5 42074605743]
2023-03-06 11:50:03 INF source db is doing bgsave. address=[172.16.13.116:6385]
2023-03-06 11:50:06 INF source db bgsave finished. timeUsed=[3.76]s, address=[172.16.13.116:6385]
2023-03-06 11:50:06 INF received rdb length. length=[104400306]
2023-03-06 11:50:06 INF create dump.rdb file. filename_path=[dump.rdb]
2023-03-06 11:50:07 INF save RDB finished. address=[172.16.13.116:6385], total_bytes=[104400306]
2023-03-06 11:50:07 INF start send RDB. address=[172.16.13.116:6385]
2023-03-06 11:50:07 INF RDB version: 9
2023-03-06 11:50:07 INF RDB AUX fields. key=[redis-ver], value=[5.0.14]
2023-03-06 11:50:07 INF RDB AUX fields. key=[redis-bits], value=[64]
2023-03-06 11:50:07 INF RDB AUX fields. key=[ctime], value=[1678074603]
2023-03-06 11:50:07 INF RDB AUX fields. key=[used-mem], value=[137563544]
2023-03-06 11:50:07 INF RDB repl-stream-db: 0
2023-03-06 11:50:07 INF RDB AUX fields. key=[repl-id], value=[f120c62558b07bc1d3826f67b9a141b3c3ace6f5]
2023-03-06 11:50:07 INF RDB AUX fields. key=[repl-offset], value=[42074605743]
2023-03-06 11:50:07 INF RDB AUX fields. key=[aof-preamble], value=[0]
2023-03-06 11:50:07 INF start save AOF. address=[172.16.13.116:6385]
2023-03-06 11:50:07 INF RDB resize db. db_size=[100004], expire_size=[0]
2023-03-06 11:50:07 INF AOFWriter open file. filename=[42074605743.aof]
2023-03-06 11:50:08 INF syncing rdb. percent=[0.00]%, allowOps=[4921.40], disallowOps=[0.00], entryId=[24607], InQueueEntriesCount=[1023], unansweredBytesCount=[1000930]bytes, rdbFileSize=[0.097]G, rdbSendSize=[0.000]G
2023-03-06 11:50:11 INF RDB resize db. db_size=[1], expire_size=[0]
2023-03-06 11:50:11 INF RDB resize db. db_size=[1], expire_size=[0]
2023-03-06 11:50:11 INF RDB resize db. db_size=[1], expire_size=[0]
2023-03-06 11:50:11 INF RDB resize db. db_size=[1], expire_size=[0]
2023-03-06 11:50:11 INF RDB resize db. db_size=[1], expire_size=[0]
2023-03-06 11:50:11 INF send RDB finished. address=[172.16.13.116:6385], repl-stream-db=[0]
2023-03-06 11:50:12 INF AOFReader open file. aof_filename=[42074605743.aof]
2023-03-06 11:50:13 INF syncing aof. allowOps=[15076.40], disallowOps=[0.00], entryId=[100024], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[42074607880], aofAppliedOffset=[42074607880]
2023-03-06 11:50:18 INF syncing aof. allowOps=[0.80], disallowOps=[0.00], entryId=[100028], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[42074608449], aofAppliedOffset=[42074608449]
2023-03-06 11:50:23 INF syncing aof. allowOps=[2.00], disallowOps=[0.00], entryId=[100038], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[42074609750], aofAppliedOffset=[42074609750]
2023-03-06 11:50:24 INF goroutine 50 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x79a4ac, 0x3}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x8167a0, 0xc0000a6060})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc00009a640, {0x816540, 0xc000098780})]<-github.com/alibaba/RedisShake/internal/reader/psync.go:202 +0x166  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1]<-github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef  [
2023-03-06 11:50:24 PNC EOF
2023-03-06 11:50:24 INF AOFWriter close file. filename=[42074605743.aof], filesize=[4007]
panic: EOF

goroutine 50 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00023e2e7, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000098540, {0xc00023e2e7, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc000098540, {0x79a4ac, 0x2c7}, {0x0, 0x79a3e6, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0x79a4ac, 0x3}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x8167a0, 0xc0000a6060})
	github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveAOF(0xc00009a640, {0x816540, 0xc000098780})
	github.com/alibaba/RedisShake/internal/reader/psync.go:202 +0x166
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
	github.com/alibaba/RedisShake/internal/reader/psync.go:48 +0xef
```

**源端 Redis**
版本：5.0.14，开源

**目的端 Redis**
版本：6.2.10，开源
目标redis 执行命令查看

```
172.16.13.116:26385> info replication
# Replication
role:master
connected_slaves:5
slave0:ip=172.16.13.117,port=26385,state=online,offset=12710086637,lag=1
slave1:ip=172.16.13.118,port=26385,state=online,offset=12710086924,lag=0
slave2:ip=172.16.13.116,port=6385,state=online,offset=12710086924,lag=0
slave3:ip=172.16.13.117,port=6385,state=online,offset=12710086637,lag=1
slave4:ip=172.16.13.118,port=6385,state=online,offset=12710086637,lag=0

172.16.13.116:26386> info replication
172.16.13.116:26386> info sentinel
# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=mymaster,status=ok,address=172.16.13.116:26385,slaves=5,sentinels=6
```

**Comment by suxb201** [comment]
https://github.com/alibaba/RedisShake/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99#pnc-eof

**Comment by yuqun20230302** [comment]
> https://github.com/alibaba/RedisShake/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99#pnc-eof

你好，我还是有点问题麻烦你一下了
![image](https://user-images.githubusercontent.com/126741318/223057472-d59e5d17-d7f4-4198-aacc-7a600247d8cf.png)
总共数据量400M，测试用，没有查询或者别的写入，client-output-buffer-limit replica 走的默认，想问一下如果数据量大了，这个值还是512M就行？不知道这个参数该如何计算修改的
master节点日志如下：
```
149321:M 06 Mar 2023 11:50:03.139 * Replica 172.16.13.116:10007 asks for synchronization
149321:M 06 Mar 2023 11:50:03.139 * Full resync requested by replica 172.16.13.116:10007
149321:M 06 Mar 2023 11:50:03.139 * Starting BGSAVE for SYNC with target: disk
149321:M 06 Mar 2023 11:50:03.175 * Background saving started by pid 190892
190892:C 06 Mar 2023 11:50:06.864 * DB saved on disk
190892:C 06 Mar 2023 11:50:06.869 * RDB: 1 MB of memory used by copy-on-write
149321:M 06 Mar 2023 11:50:06.934 * Background saving terminated with success
149321:M 06 Mar 2023 11:50:07.299 * Synchronization with replica 172.16.13.116:10007 succeeded
149321:S 06 Mar 2023 11:50:24.547 # Connection with replica 172.16.13.117:6385 lost.
149321:S 06 Mar 2023 11:50:24.547 # Connection with replica 172.16.13.118:6385 lost.
149321:S 06 Mar 2023 11:50:24.547 # Connection with replica 172.16.13.116:10007 lost.
149321:S 06 Mar 2023 11:50:24.547 * Before turning into a replica, using my master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
149321:S 06 Mar 2023 11:50:24.547 * REPLICAOF 172.16.13.116:26385 enabled (user request from 'id=291648 addr=172.16.13.118:41934 fd=14 name=sentinel-bf638c81-cmd age=10 idle=0 flags=x db=0 sub=0 psub=0 multi=3 qbuf=154 qbuf-free=32614 obl=36 oll=0 omem=0 events=r cmd=exec')
149321:S 06 Mar 2023 11:50:24.562 # CONFIG REWRITE executed with success.
149321:S 06 Mar 2023 11:50:25.105 * Connecting to MASTER 172.16.13.116:26385
```

**Comment by suxb201** [comment]
你的主节点变成备节点了？

**Comment by yuqun20230302** [comment]
> 你的主节点变成备节点了？

不是，是源redis的主节点变成目标redis的从节点了

**Comment by suxb201** [comment]
@yangbodong22011  同步过程中不要进行节点拓扑变更

**Comment by yuqun20230302** [comment]
> @yangbodong22011 同步过程中不要进行节点拓扑变更
好的，我重置了这俩redis好使了，感谢
