### ISSUE TITLE
 failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url

### ISSUE THREAD

**Issue by yuqun20230302** [aliyun/redis-shake#570]
**问题描述**
运行cluster_helper.py 报错，因为环境离线，我是通过虚拟机下载requirements.txt 中的whl文件，再去加载的。集群到集群模式
如果不用cluster_helper.py 运行正常
```
[root@k8s-master pythonPackage]# pip3 download -d offline -r requirements.txt
Collecting redis==4.3.4 (from -r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/redis-4.3.4-py3-none-any.whl
Collecting requests==2.27.1 (from -r requirements.txt (line 2))
  File was already downloaded /opt/pythonPackage/offline/requests-2.27.1-py2.py3-none-any.whl
Collecting toml==0.10.2 (from -r requirements.txt (line 3))
  File was already downloaded /opt/pythonPackage/offline/toml-0.10.2-py2.py3-none-any.whl
Collecting packaging>=20.4 (from redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/packaging-21.3-py3-none-any.whl
Collecting deprecated>=1.2.3 (from redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/Deprecated-1.2.13-py2.py3-none-any.whl
Collecting async-timeout>=4.0.2 (from redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/async_timeout-4.0.2-py3-none-any.whl
Collecting typing-extensions; python_version < "3.8" (from redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/typing_extensions-4.1.1-py3-none-any.whl
Collecting importlib-metadata>=1.0; python_version < "3.8" (from redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/importlib_metadata-4.8.3-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.27.1->-r requirements.txt (line 2))
  File was already downloaded /opt/pythonPackage/offline/certifi-2022.12.7-py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1 (from requests==2.27.1->-r requirements.txt (line 2))
  File was already downloaded /opt/pythonPackage/offline/urllib3-1.26.14-py2.py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3" (from requests==2.27.1->-r requirements.txt (line 2))
  File was already downloaded /opt/pythonPackage/offline/idna-3.4-py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests==2.27.1->-r requirements.txt (line 2))
  File was already downloaded /opt/pythonPackage/offline/charset_normalizer-2.0.12-py3-none-any.whl
Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging>=20.4->redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/pyparsing-3.0.9-py3-none-any.whl
Collecting wrapt<2,>=1.10 (from deprecated>=1.2.3->redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/wrapt-1.15.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Collecting zipp>=0.5 (from importlib-metadata>=1.0; python_version < "3.8"->redis==4.3.4->-r requirements.txt (line 1))
  File was already downloaded /opt/pythonPackage/offline/zipp-3.6.0-py3-none-any.whl
Successfully downloaded redis requests toml packaging deprecated async-timeout typing-extensions importlib-metadata certifi urllib3 idna charset-normalizer pyparsing wrapt zipp

```
![image](https://user-images.githubusercontent.com/126741318/223383405-deab8e78-24df-45f8-aa3c-3d3f46bd1725.png)
```
pip3 install --no-index --find-links=offline -r requirements.txt
```
![image](https://user-images.githubusercontent.com/126741318/223387780-632c6f49-364d-49e6-a43d-24f14a2f1cfa.png)

redis-shake 的日志：
```
edis-shake path: ../redis-shake
redis-shake abs path: /data/redis-shake3/redis-shake
{'type': 'sync', 'source': {'version': 5.0, 'address': '172.16.13.116:6383', 'username': '', 'password': 'hadoop@123', 'tls': False, 'elasticache_psync': ''}, 'target': {'type': 'cluster', 'version': 6.2, 'address': '172.16.13.116:26383', 'username': '', 'password': 'hadoop@123', 'tls': False}, 'advanced': {'dir': '/data/redis-shake3/data/cluster2cluster', 'ncpu': 4, 'pprof_port': 9310, 'metrics_port': 9320, 'log_file': 'redis-shake_cluster2cluster.log', 'log_level': 'info', 'log_interval': 5, 'rdb_restore_command_behavior': 'rewrite', 'pipeline_count_limit': 1024, 'target_redis_client_max_querybuf_len': 1024000000, 'target_redis_proto_max_bulk_len': 512000000}}
host: 172.16.13.116, port: 6383, username: , password: hadoop@123, tls: False
cluster nodes: {'172.16.13.118:6383': {'node_id': '52c3baacb555dd7cb5bcf5f6e4acac5af43d7d7c', 'flags': 'myself,master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181198000', 'epoch': '3', 'slots': [['10923', '16383']], 'migrations': [], 'connected': True}, '172.16.13.118:6384': {'node_id': '3fcab27ed3effc67785e56a3aa2033426b7ea622', 'flags': 'slave', 'master_id': 'b326865027006ef579fdf5ea9ba1cff180dbde62', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181200234', 'epoch': '6', 'slots': [], 'migrations': [], 'connected': True}, '172.16.13.116:6383': {'node_id': 'e63a5ead5c2fd7f7ee9ff91eb3af2e84241d73c7', 'flags': 'master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181198226', 'epoch': '1', 'slots': [['0', '5460']], 'migrations': [], 'connected': True}, '172.16.13.116:6384': {'node_id': 'ddb1f8186345eb41dd46791834f8fead9c1c12ab', 'flags': 'slave', 'master_id': '52c3baacb555dd7cb5bcf5f6e4acac5af43d7d7c', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181202241', 'epoch': '4', 'slots': [], 'migrations': [], 'connected': True}, '172.16.13.117:6384': {'node_id': 'f90b316c3f2182d9d54056f433b84290ad9cbc19', 'flags': 'slave', 'master_id': 'e63a5ead5c2fd7f7ee9ff91eb3af2e84241d73c7', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181199229', 'epoch': '5', 'slots': [], 'migrations': [], 'connected': True}, '172.16.13.117:6383': {'node_id': 'b326865027006ef579fdf5ea9ba1cff180dbde62', 'flags': 'master', 'master_id': '-', 'last_ping_sent': '0', 'last_pong_rcvd': '1678181201000', 'epoch': '2', 'slots': [['5461', '10922']], 'migrations': [], 'connected': True}}
addresses:
172.16.13.118:6383
172.16.13.116:6383
172.16.13.117:6383
start syncing...
sleep 3 seconds to wait redis-shake start
================ 2023-03-07 17:26:39 ================
get metrics from [172.16.13.118:6383] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e4a588>: Failed to establish a new connection: [Errno 111] Connection refused',))
get metrics from [172.16.13.117:6383] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e057f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
172.16.13.116:6383  
================ 2023-03-07 17:26:44 ================
get metrics from [172.16.13.118:6383] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e34f28>: Failed to establish a new connection: [Errno 111] Connection refused',))
get metrics from [172.16.13.117:6383] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e05630>: Failed to establish a new connection: [Errno 111] Connection refused',))
172.16.13.116:6383 syncing rdb. percent=[0.00]%, allowOps=[2856.40], disallowOps=[0.00], entryId=[14282], InQueueEntriesCount=[1024], unansweredBytesCount=[1098656]bytes, rdbFileSize=[0.098]G, rdbSendSize=[0.000]G 
================ 2023-03-07 17:26:49 ================
get metrics from [172.16.13.118:6383] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e05ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
get metrics from [172.16.13.117:6383] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e200b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
172.16.13.116:6383 syncing aof. allowOps=[17142.80], disallowOps=[0.00], entryId=[100002], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[18761483302], aofAppliedOffset=[18761483302] 
================ 2023-03-07 17:26:54 ================
get metrics from [172.16.13.118:6383] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e16c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
get metrics from [172.16.13.117:6383] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e4a9e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
172.16.13.116:6383 syncing aof. allowOps=[0.20], disallowOps=[0.00], entryId=[100003], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[18761483316], aofAppliedOffset=[18761483316] 
================ 2023-03-07 17:26:59 ================
get metrics from [172.16.13.118:6383] failed: HTTPConnectionPool(host='localhost', port=11008): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e4aeb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
get metrics from [172.16.13.117:6383] failed: HTTPConnectionPool(host='localhost', port=11010): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7f2e05b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
172.16.13.116:6383 syncing aof. allowOps=[0.00], disallowOps=[0.00], entryId=[100003], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[18761483316], aofAppliedOffset=[18761483316] 

```

---

**源端 Redis**
版本：5，自建
日志：
```
145409:M 07 Mar 2023 17:26:36.774 * Replica 172.16.13.116:10007 asks for synchronization
145409:M 07 Mar 2023 17:26:36.774 * Full resync requested by replica 172.16.13.116:10007
145409:M 07 Mar 2023 17:26:36.774 * Starting BGSAVE for SYNC with target: disk
145409:M 07 Mar 2023 17:26:36.826 * Background saving started by pid 603357
603357:C 07 Mar 2023 17:26:40.478 * DB saved on disk
603357:C 07 Mar 2023 17:26:40.483 * RDB: 1 MB of memory used by copy-on-write
145409:M 07 Mar 2023 17:26:40.542 * Background saving terminated with success
145409:M 07 Mar 2023 17:26:41.005 * Synchronization with replica 172.16.13.116:10007 succeeded
145409:M 07 Mar 2023 17:27:21.998 # Connection with replica 172.16.13.116:10007 lost.
```

---

**目的端 Redis**
版本：6.2，集群 自建
日志：
```

```
后来去cluster_helper 目录下生成的data目录里查看stderr日志
```
panic: unexpected EOF

goroutine 24 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0004aef00, 0x0})
        github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000098d80, {0xc0004aef00, 0xe})
        github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc000098d80, {0x79ec5d, 0x712}, {0x0, 0x79a3e6, 0x3})
        github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0x79ec5d, 0xe}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x8167a0, 0xc0000a6070})
        github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/rdb/structure.ReadBytes({0x816a40, 0xc0002a2f20}, 0xc000054800)
        github.com/alibaba/RedisShake/internal/rdb/structure/byte.go:17 +0x65
github.com/alibaba/RedisShake/internal/rdb/structure.ReadString({0x816a40, 0xc0002a2f20})
        github.com/alibaba/RedisShake/internal/rdb/structure/string.go:42 +0x1a7
github.com/alibaba/RedisShake/internal/rdb/types.(*StringObject).LoadFromBuffer(...)
        github.com/alibaba/RedisShake/internal/rdb/types/string.go:15
github.com/alibaba/RedisShake/internal/rdb/types.ParseObject({0x816a40, 0xc0002a2f20}, 0x0, {0xc0004fbbc0, 0x480})
        github.com/alibaba/RedisShake/internal/rdb/types/interface.go:71 +0xcc
github.com/alibaba/RedisShake/internal/rdb.(*Loader).parseRDBEntry(0xc000138000, 0xc000286240)
        github.com/alibaba/RedisShake/internal/rdb/rdb.go:156 +0x7a6
github.com/alibaba/RedisShake/internal/rdb.(*Loader).ParseRDB(0xc000138000)
        github.com/alibaba/RedisShake/internal/rdb/rdb.go:85 +0x3f7
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendRDB(0xc00009a640)
        github.com/alibaba/RedisShake/internal/reader/psync.go:214 +0xbd
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
        github.com/alibaba/RedisShake/internal/reader/psync.go:49 +0xf9
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
        github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f
```
后来去cluster_helper 目录下生成的data目录里查看sync.toml
```
type = "sync"

[source]
version = 5.0
address = "172.16.13.116:6383"
username = ""
password = "hadoop@123"
tls = false
elasticache_psync = ""

[target]
type = "cluster"
version = 6.2
address = "172.16.13.116:26383"
username = ""
password = "hadoop@123"
tls = false

[advanced]
dir = "/data/redis-shake3/data/cluster2cluster"
ncpu = 4
pprof_port = 0
metrics_port = 11009
log_file = "redis-shake_cluster2cluster.log"
log_level = "info"
log_interval = 5
rdb_restore_command_behavior = "rewrite"
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1024000000
target_redis_proto_max_bulk_len = 512000000

```
和pprof_port 、metrics_port有关联么，我如果设置pprof_port 报错提示pprof_port 端口已被占用

**Comment by yuqun20230302** [comment]
我发现三主三从的集群创建的三个主节点的信息，有两个报错，一个正常数据迁移

**Comment by yuqun20230302** [comment]
我发现三主三从的集群创建的三个主节点的信息，有两个报错，一个正常数据迁移

**Comment by suxb201** [comment]
@yuqun20230302 手动开启 3 个 shake 试试呢
