### ISSUE TITLE
RedisShake 是否支持同步Azure Redis？

### ISSUE THREAD

**Issue by wstest123** [aliyun/redis-shake#573]
**问题描述**
RedisShake 是否支持同步Azure Redis？

**Comment by suxb201** [comment]
想兼容，但是手上没有 Azure 资源测试 😭
你可以用下试试，遇到问题我帮看下

**Comment by wstest123** [comment]
Hi @suxb201 在做测试的时候遇到了PNC ERR Command disallowed 的问题
[created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead]<-github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f PNC ERR Command disallowed

**Comment by suxb201** [comment]
@wstest123 版本是哪个？另外麻烦提供更多日志。

**Comment by plutoid** [comment]
azure redis版本，同样的问题，不过我记得老点的redis-shake能工作

# Server
redis_version:4.0.14
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
run_id:6a9a6611310b28b2a1291d825343178d79e8f4de
uptime_in_seconds:54844
uptime_in_days:0
hz:10

**Comment by suxb201** [comment]
@plutoid 请提供 shake 报错日志

**Comment by jasonyuzhenyang** [comment]
@suxb201  我测试了azure redis 4 到6版本sync，错误日志和上面类似，请帮忙看下是否azure redis也不支持psync命令。完整日志如下：
2023-04-19 18:37:28 INF GOOS: linux, GOARCH: amd64
2023-04-19 18:37:28 INF Ncpu: 2, GOMAXPROCS: 2
2023-04-19 18:37:28 INF pid: 7906
2023-04-19 18:37:28 INF pprof_port: 0
2023-04-19 18:37:28 INF No lua file specified, will not filter any cmd.
2023-04-19 18:37:28 INF auth successful. address=[azure-6.redis.cache.windows.net:6380]
2023-04-19 18:37:28 INF redisWriter connected to redis successful. address=[azure-6.redis.cache.windows.net:6380]
2023-04-19 18:37:28 INF auth successful. address=[azure-4.redis.cache.windows.net:6380]
2023-04-19 18:37:28 INF psyncReader connected to redis successful. address=[azure-4.redis.cache.windows.net:6380]
2023-04-19 18:37:28 WRN remove file. filename=[232962340.aof]
2023-04-19 18:37:28 WRN remove file. filename=[dump.rdb]
2023-04-19 18:37:28 INF start save RDB. address=[azure-4.redis.cache.windows.net:6380]
2023-04-19 18:37:28 INF send [replconf listening-port 10007]
2023-04-19 18:37:28 INF goroutine 24 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc000028330, 0x16}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x8731a0?, 0xc0000385f0?})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc0000241e0, {0xc0001f2de0?, 0xc00012bf68?, 0x1?})]<-github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc000080320)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()]<-github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x6f  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead]<-github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8d  [
2023-04-19 18:37:28 PNC ERR Command disallowed
panic: ERR Command disallowed

goroutine 24 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000028360?, 0x0?})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000076d80, {0xc000028360, 0x16})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2d8
github.com/rs/zerolog.(*Event).Msgf(0xc000076d80, {0xc000028330?, 0x401?}, {0x0?, 0x7dc5b2?, 0x3?})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc000028330, 0x16}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x8731a0?, 0xc0000385f0?})
	github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc0000241e0, {0xc0001f2de0?, 0xc00012bf68?, 0x1?})
	github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc000080320)
	github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
	github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x6f
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
	github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8d

**Comment by suxb201** [comment]
看起来是不支持，你可以使用 redis-cli 连接上 azure，分别执行下这两条命令验证一下：
```
replconf listening-port 10007
psync ? -1
```
如果 psync 没有权限说明不支持了，可以考虑向 AZURE 提个工单看看能给你开权限吗，实在不行只能通过 rdb 的方式向外迁了。

**Comment by jasonyuzhenyang** [comment]
psync 权限验证失败，应该是不支持的。
![image](https://user-images.githubusercontent.com/131262439/233242796-cc1dad65-0a74-480a-801e-fa4f5230bdbd.png)

**Comment by suxb201** [comment]
@plutoid @wstest123 @jasonyuzhenyang 总结一下是 Azure 禁用了相关命令，导致不能随意把数据迁出。建议：
1. 理论上 Azure 应该能给你们开这些命令的权限，单纯不想开，可以提工单试一试，说不定就给开权限了。参考 AWS：https://tair-opensource.github.io/RedisShake/zh/guide/mode.html#aws-elasticache-and-memorydb
2. 实在不给开，可以考虑试一下 scan 模式，性能差但是能用，现在也支持增量了。
