### ISSUE TITLE
sync同步报错write: broken pipe

### ISSUE THREAD

**Issue by boboboboboli** [aliyun/redis-shake#586]
**问题描述**
源集群是redis cluster 4.0.12 三主三从
目标集群是redis cluster 4.0.12 三主三从
源集群1900w+的key，mem大概10G，做之前先把目标集群清空数据，redis-trib.rb call xxxx:xx flush_all async

sync.toml模板如下：
```
type = "sync"
[source]
version = 4.0
address = "xx.xx.x.xxx:6379"
username = ""
password = "xxxxxxxxx"
tls = false
elasticache_psync = ""
[target]
type = "cluster"
version = 4.0
address = "yy.yyy.y.yy:6379"
username = ""
password = "yyyyyyyyyy"
tls = false
[advanced]
dir = "data2"
ncpu = 1
pprof_port = 0
metrics_port = 0
log_file = "sync2.log"
log_level = "debug"
log_interval = 5
rdb_restore_command_behavior = "rewrite"
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1024_000_000
target_redis_proto_max_bulk_len = 512_000_000
```
手动启动三个通道复制（三个配置文件大概如上模板，只是改了source address、dir、log_file等必要配置）
```
cd /appdata/redis-shake_new/
nohup /appdata/redis-shake_new/redis-shake /appdata/redis-shake_new/sync1.toml /appdata/redis-shake_new/filters/aws.lua &
nohup /appdata/redis-shake_new/redis-shake /appdata/redis-shake_new/sync2.toml /appdata/redis-shake_new/filters/aws.lua &
nohup /appdata/redis-shake_new/redis-shake /appdata/redis-shake_new/sync3.toml /appdata/redis-shake_new/filters/aws.lua &
```
然后可以看到正常在复制，load完rdb文件到目标集群后，就出现报错了。日志如下：
redis-shake 的日志：
```
{"level":"info","time":"2023-04-07T02:32:45+08:00","message":"syncing rdb. percent=[96.88]%, allowOps=[73141.80], disallowOps=[0.00], entryId=[18812731], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, rdbFileSize=[4.056]G, rdbSendSize=[3.930]G"}
{"level":"info","time":"2023-04-07T02:32:50+08:00","message":"syncing rdb. percent=[98.63]%, allowOps=[73871.80], disallowOps=[0.00], entryId=[19182090], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, rdbFileSize=[4.056]G, rdbSendSize=[4.001]G"}
{"level":"info","time":"2023-04-07T02:32:53+08:00","message":"LUA script: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('hincrby', KEYS[1], ARGV[3], -1); if (counter > 0) then redis.call('pexpire', KEYS[1], ARGV[2]); return 0; else redis.call('del', KEYS[1]); redis.call('publish', KEYS[2], ARGV[1]); return 1; end; return nil;]"}
{"level":"info","time":"2023-04-07T02:32:53+08:00","message":"LUA script: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);]"}
{"level":"info","time":"2023-04-07T02:32:53+08:00","message":"send RDB finished. address=[xxx.xxx.xxx.xxx:6379], repl-stream-db=[0]"}
{"level":"info","time":"2023-04-07T02:32:53+08:00","message":"goroutine 1 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc01878b8b0, 0x41}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x816b20, 0xc0189410e0})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).flush(0xc0001d1640)]<-github.com/alibaba/RedisShake/internal/client/redis.go:100 +0x2a  [github.com/alibaba/RedisShake/internal/client.(*Redis).SendBytes(0xc0000241c0, {0xc0181a9340, 0xa7a4f8, 0xc000010810})]<-github.com/alibaba/RedisShake/internal/client/redis.go:94 +0x45  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).Write(0xc0001d1600, 0xc018bbc820)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:54 +0x12d  [github.com/alibaba/RedisShake/internal/writer.(*RedisClusterWriter).Write(0xc018bbc820, 0xc018bbc820)]<-github.com/alibaba/RedisShake/internal/writer/redis_cluster.go:100 +0x92  [main.main()]<-github.com/alibaba/RedisShake/cmd/redis-shake/main.go:109 +0x7fa  ["}
{"level":"panic","time":"2023-04-07T02:32:53+08:00","message":"write tcp xxx.xxx.xxx.xxx:59328->xxx.xxx.xxx.xxx:6379: write: broken pipe"}
```
三个通道都是percent=[98.63]%接近100%后就报错了。错误一模一样。
此时，
**目标端 Redis** 无异常日志：
**源端 Redis**日志如下（源端client -output-buffer-limit配置normal 0 0 0 slave 1073741824 1073741824 60 pubsub 33554432 8388608 60 ）：
```
19350:M 07 Apr 01:24:05.637 * Slave xx.xxx.x.xx:9320 asks for synchronization
19350:M 07 Apr 01:24:05.637 * Full resync requested by slave xx.xxx.x.xx:9320
19350:M 07 Apr 01:24:05.637 * Starting BGSAVE for SYNC with target: disk
19350:M 07 Apr 01:24:05.935 * Background saving started by pid 14354
14354:C 07 Apr 01:25:30.520 * DB saved on disk
14354:C 07 Apr 01:25:30.754 * RDB: 473 MB of memory used by copy-on-write
19350:M 07 Apr 01:25:31.226 * Background saving terminated with success
19350:M 07 Apr 01:39:05.583 # Connection with slave client id #247798504 lost.
19350:M 07 Apr 01:45:46.929 * Slave xx.xxx.x.xx:10007 asks for synchronization
19350:M 07 Apr 01:45:46.929 * Full resync requested by slave xx.xxx.x.xx:10007
19350:M 07 Apr 01:45:46.929 * Starting BGSAVE for SYNC with target: disk
19350:M 07 Apr 01:45:47.242 * Background saving started by pid 22856
22856:C 07 Apr 01:47:10.839 * DB saved on disk
22856:C 07 Apr 01:47:11.121 * RDB: 442 MB of memory used by copy-on-write
19350:M 07 Apr 01:47:11.619 * Background saving terminated with success
19350:M 07 Apr 01:47:23.397 * Synchronization with slave xx.xxx.x.xx:10007 succeeded
19350:M 07 Apr 01:52:58.445 # Connection with slave client id #247820279 lost.
19350:M 07 Apr 02:07:08.233 * Slave xx.xxx.x.xx:10007 asks for synchronization
19350:M 07 Apr 02:07:08.233 * Full resync requested by slave xx.xxx.x.xx:10007
19350:M 07 Apr 02:07:08.233 * Starting BGSAVE for SYNC with target: disk
19350:M 07 Apr 02:07:08.547 * Background saving started by pid 31324
31324:C 07 Apr 02:08:31.640 * DB saved on disk
31324:C 07 Apr 02:08:31.901 * RDB: 430 MB of memory used by copy-on-write
19350:M 07 Apr 02:08:32.349 * Background saving terminated with success
19350:M 07 Apr 02:08:42.846 * Synchronization with slave xx.xxx.x.xx:10007 succeeded
19350:M 07 Apr 02:14:00.772 # Connection with slave client id #247841939 lost.
```
该集群有使用redisson分布式锁，分布式锁的命令大致如下：
```
加锁
r eval "if (redis.call('exists',KEYS[1]) == 0) then redis.call('hincrby',KEYS[1],ARGV[2],1); redis.call('pexpire',KEYS[1],ARGV[1]); return nil; end; if (redis.call('hexists',KEYS[1],ARGV[2]) == 1) then redis.call('hincrby',KEYS[1],ARGV[2],1); redis.call('pexpire',KEYS[1],ARGV[1]); return nil; end; return redis.call('pttl',KEYS[1]);" 1 "rlock_03_1410324200208053110" "30000" "xxxxxxxx-xxx-xxxxxx-xxxx-xxxxxxxxxx:136529" 
延长锁
r eval "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); return 1; end; return 0;" 1 "rlock_03_1410324200208053110" "30000" "xxxxxxxx-xxx-xxxxxx-xxxx-xxxxxxxxxx:136529" 
解锁
r eval "if (redis.call('hexists',KEYS[1],ARGV[3]) == 0 ) then return nil;end; local counter = redis.call('hincrby',KEYS[1],ARGV[3],-1); if (counter > 0) then redis.call('pexpire',KEYS[1],ARGV[2]); return 0;else redis.call('del',KEYS[1]); redis.call('publish',KEYS[2],ARGV[1]); return 1; end;return nil;" "2" "rlock_03_1410324200208053110" "redisson_lock_channel:{rlock_03_1410324200208053110}" "0" "30000" "xxxxxxxx-xxx-xxxxxx-xxxx-xxxxxxxxxx:136529"
```
我一直怀疑是分布式锁导致问题，所以做了如下尝试，但都失败了。
我尝试过使用2.x版本的redis-shake，把filter.lua 设置为true和false都失败了。
使用3.x版本，配置aws.lua 过滤REPLCONF命令失败了，配置key_prefix.lua过滤redisson相关key rlock_* 也失败了，配置skip_scripts.lua 过滤所有eval脚本也失败了。尝试调整pipeline_count_limit = 512  target_redis_client_max_querybuf_len = 512_000_000 target_redis_proto_max_bulk_len = 256_000_000 也失败了
我尝试在源端其中一个master节点开启monitor，获取到的命令大概有expire / zrangebyscore / eval /wait /setex /ping /del /auth /sismember 还有lua里面的exists/hincrby/pexpire/hexists/del/publish等命令

麻烦大佬帮忙看看 ，谢谢

**Comment by suxb201** [comment]
1. 不要在同一个目录启动多个 redis-shake，因为 redis-shake 会在本地存储临时文件，多个 redis-shake 之间的临时文件会干扰，正确做法是建立多个目录。
2. `"write tcp xxx.xxx.xxx.xxx:59328->xxx.xxx.xxx.xxx:6379: write: broken pipe"} ` 6379 的 ip 是目的端还是源端？
 如果是目的端，确认下运行 redis-shake 的集群到目的端网络是否稳定，是否有跨国网络之类的情况。

**Comment by boboboboboli** [comment]
1.不要在同一个目录启动多个 redis-shake，因为 redis-shake 会在本地存储临时文件，多个 redis-shake 之间的临时文件会干扰，正确做法是建立多个目录。
是多个目录，分别在/appdata/redis-shake_new/data1 和/appdata/redis-shake_new/data2 和 /appdata/redis-shake_new/data3

2."write tcp xxx.xxx.xxx.xxx:59328->xxx.xxx.xxx.xxx:6379: write: broken pipe"}  6379 的 ip 是目的端还是源端？  是目标端
如果是目的端，确认下运行 redis-shake 的集群到目的端网络是否稳定，是否有跨国网络之类的情况。 同个网段，应该是稳定的。

**Comment by boboboboboli** [comment]
源端配置了timeout 120不知道是否有影响

**Comment by suxb201** [comment]
> 源端配置了timeout 120不知道是否有影响

应该没影响，本身是有保活的，且看日志是目的端连接断了。想不明白哪里会有问题，还是考虑你本身网络等环境的问题。建议你再次尝试一下，然后给出三个 shake 的日志。如果能抓包看下连接是如何断开的也好。

**Comment by boboboboboli** [comment]
在目标集群将timeout参数由120调整为3600后解决了，关闭此问题。

**Comment by boboboboboli** [comment]
关闭
