### ISSUE TITLE
不支持阿里云云数据库Redis 4.0

### ISSUE THREAD

**Issue by nsnake** [aliyun/redis-shake#588]
两边都是阿里云社区4.0单机版，已经设置了账户和密码开启了复制的权限，其中阿里云账户登陆的格式为
用户名:密码
不管在username或password中使用上面的格式都无法登陆redis

其中
在同步的时失败。以下是错误信息
`
2023-04-12 11:39:03 INF goroutine 8 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc000208000, 0x31}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x8172a0, 0xc00020a000})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc0000a2060, {0xc0001b4390, 0xc00003ff68, 0x1})]<-github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc0000be000)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()]<-github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x72  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead]<-github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f  [
2023-04-12 11:58:22 PNC NOAUTH Authentication required.
panic: NOAUTH Authentication required.

goroutine 8 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000208040, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0002000c0, {0xc000208040, 0x31})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc0002000c0, {0xc000208000, 0x3fb}, {0x0, 0x79a3e6, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc000208000, 0x31}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x8172a0, 0xc00020a000})
	github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc0000a2060, {0xc0001b4390, 0xc00003ff68, 0x1})
	github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc0000be000)
	github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
	github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x72
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
	github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f
`

**Comment by suxb201** [comment]
你应该用开启复制权限的账号

**Comment by suxb201** [comment]
也请提供全量的 shake 日志

**Comment by nsnake** [comment]
已经知道原因了，对应账户没建好，另外就是把用户名和密码按格式写在password的位置即可
