### ISSUE TITLE
使用cluster_helper迁移5.0版本至6.2版本集群报错

### ISSUE THREAD

**Issue by chaochensd** [aliyun/redis-shake#604]
**问题描述**

集群三个node中的一个迁移同步失败，具体日志如下

cluster_helper 的日志：
```
addresses:
10.140.0.60:5000
10.140.0.60:5002
10.140.0.60:5001
start syncing...
sleep 3 seconds to wait redis-shake start
================ 2023-05-11 09:01:52 ================
10.140.0.60:5000  
10.140.0.60:5001  
10.140.0.60:5002  
================ 2023-05-11 09:01:57 ================
get metrics from [10.140.0.60:5001] failed: HTTPConnectionPool(host='localhost', port=11114): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f065328b4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
10.140.0.60:5000 syncing rdb. percent=[74.75]%, allowOps=[15325.20], disallowOps=[0.00], entryId=[76625], InQueueEntriesCount=[668], unansweredBytesCount=[111322]bytes, rdbFileSize=[0.030]G, rdbSendSize=[0.022]G 
10.140.0.60:5002 syncing rdb. percent=[57.23]%, allowOps=[13051.20], disallowOps=[0.00], entryId=[65255], InQueueEntriesCount=[372], unansweredBytesCount=[18256]bytes, rdbFileSize=[0.029]G, rdbSendSize=[0.017]G 
================ 2023-05-11 09:02:02 ================
get metrics from [10.140.0.60:5001] failed: HTTPConnectionPool(host='localhost', port=11114): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f065328bb38>: Failed to establish a new connection: [Errno 111] Connection refused',))
10.140.0.60:5000 syncing aof. allowOps=[2159.20], disallowOps=[0.00], entryId=[87421], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[317385318454], aofAppliedOffset=[317385318454] 
10.140.0.60:5002 syncing aof. allowOps=[4469.20], disallowOps=[0.00], entryId=[87601], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[1494291443425], aofAppliedOffset=[1494291443425] 
================ 2023-05-11 09:02:07 ================
get metrics from [10.140.0.60:5001] failed: HTTPConnectionPool(host='localhost', port=11114): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f065322c390>: Failed to establish a new connection: [Errno 111] Connection refused',))
10.140.0.60:5000 syncing aof. allowOps=[25.20], disallowOps=[0.00], entryId=[87547], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[317385400887], aofAppliedOffset=[317385400887] 
10.140.0.60:5002 syncing aof. allowOps=[52.80], disallowOps=[0.00], entryId=[87865], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[0], aofReceivedOffset=[1494291589863], aofAppliedOffset=[1494291589863] 
```
其中失败node 5001的redis-shake日志:
```
{"level":"info","time":"2023-05-11T09:01:51Z","message":"received rdb length. length=[43785983]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"create dump.rdb file. filename_path=[dump.rdb]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"save RDB finished. address=[10.140.0.60:5001], total_bytes=[43785983]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"start send RDB. address=[10.140.0.60:5001]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB version: 9"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[redis-ver], value=[5.0.8]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[redis-bits], value=[64]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[ctime], value=[1683795709]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[used-mem], value=[77703864]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB repl-stream-db: 0"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[repl-id], value=[cafca021cad15f3ea27184595e6f40cb448963ef]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[repl-offset], value=[279573081657]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB AUX fields. key=[aof-preamble], value=[0]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"RDB resize db. db_size=[87973], expire_size=[85524]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"start save AOF. address=[10.140.0.60:5001]"}
{"level":"info","time":"2023-05-11T09:01:51Z","message":"AOFWriter open file. filename=[279573081657.aof]"}
{"level":"info","time":"2023-05-11T09:01:54Z","message":"syncing rdb. percent=[52.37]%, allowOps=[13386.00], disallowOps=[0.00], entryId=[66929], InQueueEntriesCount=[400], unansweredBytesCount=[0]bytes, rdbFileSize=[0.041]G, rdbSendSize=[0.021]G"}
{"level":"info","time":"2023-05-11T09:01:55Z","message":"goroutine 6 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc000084f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0000a69c0)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  ["}
{"level":"panic","time":"2023-05-11T09:01:55Z","message":"redisWriter received error. error=[ERR Bad data format], argv=[restore bf_reg 0 \u0007\ufffd0\u0016墉\ufffd\ufffd\u0003\u0002\ufffd\u0000\u001e \ufffd\u0002\u0001\u0002\u0004\u0002\ufffd\u0000ժw\u0004{\u0014\ufffdG\ufffdz\ufffd?\u0002\u0007\u0004\ufffd\u0016\ufffdŌ+#@\u0002\u0000\u0002\u001b\u0005À\u0000\ufffdL^\ufffd\u0001\u0000\u0000\u0000\u0014\u0000 \u00008\u0000\u0000\ufffd\u0000\u0010(\t\u0000\u0010\u0000 \u0000\u0000@B\ufffd\u0000 \u0000\u0000\u0001 \r\u0003\u0000\u0004\u0010\ufffd \u0010\u0002\ufffd\b\ufffd@!\u0002$\u0000\u0002 \u0017 \u0004\u0001\u0001\u000b \u0006\u0002\u0000(P \u0004\u0000\u0004 \u0018\u000b\ufffd\u0004\ufffd\u0001B\u0000@\b\u0002\u0005\u0003D \u000e\u0002\u0000\ufffd\b 3\t\u0000 \u0001\u0004\u0002$\u0000\ufffd\ufffd@ $\u0006 \u0004@@\u0001\fF P@>
```

---

**源端 Redis**
版本：5.0，自建

---

**目的端 Redis**
版本：6.2  (redis enterprise订阅服务)
备注: 通过开启OSS Cluster API 兼容 cluster指令集

**Comment by suxb201** [comment]
是有 module  源端开启但是目的端没开启吗，比如 Bloom filter

**Comment by chaochensd** [comment]
谢谢，是因为源端开启了 Bloom filter，我这边将目标端的Bloom filter也开启后，问题得到了解决
