### ISSUE TITLE
使用SYNC模式从单机向集群复制出现报错

### ISSUE THREAD

**Issue by Knomori** [aliyun/redis-shake#612]
**问题描述**

使用SYNC模式从单机向集群复制出现报错：panic: redisWriter received error. error=[ERR SELECT is not allowed in cluster mode]

使用的redis-shake版本是3.1.10。源为单机redis，默认database:16 ， 目的为redis6.2.10的集群，3主6从。

redis-shake 的日志：

```shell
2023-05-22 16:00:39 INF GOOS: linux, GOARCH: amd64
2023-05-22 16:00:39 INF Ncpu: 4, GOMAXPROCS: 4
2023-05-22 16:00:39 INF pid: 12447
2023-05-22 16:00:39 INF pprof_port: 0
2023-05-22 16:00:39 INF No lua file specified, will not filter any cmd.
2023-05-22 16:00:39 INF auth successful. address=[10.189.60.49:8230]
2023-05-22 16:00:39 INF redisClusterWriter load cluster nodes. line=827d7dd6e013b922e529f25631f52f6d356b4259 10.189.60.43:8234@18234 master - 0 1684742439013 3 connected 10923-16383
2023-05-22 16:00:39 INF auth successful. address=[10.189.60.43:8234]
2023-05-22 16:00:39 INF redisWriter connected to redis successful. address=[10.189.60.43:8234]
2023-05-22 16:00:39 INF redisClusterWriter load cluster nodes. line=f480fd0c7f59b600f286f476ebd67e94144420e7 10.189.60.49:8230@18230 myself,master - 0 1684742436000 1 connected 0-5460
2023-05-22 16:00:39 INF auth successful. address=[10.189.60.49:8230]
2023-05-22 16:00:39 INF redisWriter connected to redis successful. address=[10.189.60.49:8230]
2023-05-22 16:00:39 INF redisClusterWriter load cluster nodes. line=02e75a78385d03a67ca98a53edc486019863ca21 10.189.60.23:8232@18232 master - 0 1684742437000 2 connected 5461-10922
2023-05-22 16:00:39 INF auth successful. address=[10.189.60.23:8232]
2023-05-22 16:00:39 INF redisWriter connected to redis successful. address=[10.189.60.23:8232]
2023-05-22 16:00:39 INF redisClusterWriter connected to redis cluster successful. addresses=[10.189.60.43:8234 10.189.60.49:8230 10.189.60.23:8232]
2023-05-22 16:00:39 INF no password. address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF psyncReader connected to redis successful. address=[10.189.60.43:7800]
2023-05-22 16:00:39 WRN remove file. filename=[608918.aof]
2023-05-22 16:00:39 WRN remove file. filename=[dump.rdb]
2023-05-22 16:00:39 INF start save RDB. address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF send [replconf listening-port 10007]
2023-05-22 16:00:39 INF send [PSYNC ? -1]
2023-05-22 16:00:39 INF receive [FULLRESYNC 9df7f8be15ef15536ec017d80cfaf12289b92e08 608946]
2023-05-22 16:00:39 INF source db is doing bgsave. address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF source db bgsave finished. timeUsed=[0.31]s, address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF received rdb length. length=[15188213]
2023-05-22 16:00:39 INF create dump.rdb file. filename_path=[dump.rdb]
2023-05-22 16:00:39 INF save RDB finished. address=[10.189.60.43:7800], total_bytes=[15188213]
2023-05-22 16:00:39 INF start send RDB. address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF RDB version: 8
2023-05-22 16:00:39 INF RDB AUX fields. key=[redis-ver], value=[4.0.2]
2023-05-22 16:00:39 INF RDB AUX fields. key=[redis-bits], value=[64]
2023-05-22 16:00:39 INF RDB AUX fields. key=[ctime], value=[1684742439]
2023-05-22 16:00:39 INF RDB AUX fields. key=[used-mem], value=[234097688]
2023-05-22 16:00:39 INF RDB repl-stream-db: -1
2023-05-22 16:00:39 INF RDB AUX fields. key=[repl-id], value=[9df7f8be15ef15536ec017d80cfaf12289b92e08]
2023-05-22 16:00:39 INF start save AOF. address=[10.189.60.43:7800]
2023-05-22 16:00:39 INF AOFWriter open file. filename=[608946.aof]
2023-05-22 16:00:39 INF RDB AUX fields. key=[repl-offset], value=[608946]
2023-05-22 16:00:39 INF RDB AUX fields. key=[aof-preamble], value=[0]
2023-05-22 16:00:39 INF RDB resize db. db_size=[11181], expire_size=[0]
2023-05-22 16:00:40 INF send RDB finished. address=[10.189.60.43:7800], repl-stream-db=[-1]
2023-05-22 16:00:41 INF AOFReader open file. aof_filename=[608946.aof]
2023-05-22 16:00:43 INF goroutine 19 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc000096f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000024140)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  [
2023-05-22 16:00:43 PNC redisWriter received error. error=[ERR SELECT is not allowed in cluster mode], argv=[PING], slots=[], reply=[<nil>]
panic: redisWriter received error. error=[ERR SELECT is not allowed in cluster mode], argv=[PING], slots=[], reply=[<nil>]

goroutine 19 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc00142e000, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc001422000, {0xc00142e000, 0x73})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc001422000, {0x7b2730, 0x21d}, {0xc007f8df78, 0x79a3e6, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc007f8df78, 0x4, 0x4})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000024140)
	github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
	github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c
```

---

**源端 Redis**
版本：自建 redis4.0.2，默认database配置为16
日志：

```
31094:M 22 May 16:00:17.126 * Slave 10.189.234.152:10007 asks for synchronization
31094:M 22 May 16:00:17.126 * Full resync requested by slave 10.189.234.152:10007
31094:M 22 May 16:00:17.126 * Starting BGSAVE for SYNC with target: disk
31094:M 22 May 16:00:17.130 * Background saving started by pid 279061
279061:C 22 May 16:00:17.398 * DB saved on disk
279061:C 22 May 16:00:17.401 * RDB: 0 MB of memory used by copy-on-write
31094:M 22 May 16:00:17.484 * Background saving terminated with success
31094:M 22 May 16:00:17.530 * Synchronization with slave 10.189.234.152:10007 succeeded
31094:M 22 May 16:00:23.725 # Connection with slave 10.189.234.152:10007 lost.
31094:M 22 May 16:00:39.091 * Slave 10.189.234.152:10007 asks for synchronization
31094:M 22 May 16:00:39.091 * Full resync requested by slave 10.189.234.152:10007
31094:M 22 May 16:00:39.091 * Starting BGSAVE for SYNC with target: disk
31094:M 22 May 16:00:39.094 * Background saving started by pid 281773
281773:C 22 May 16:00:39.363 * DB saved on disk
281773:C 22 May 16:00:39.366 * RDB: 0 MB of memory used by copy-on-write
31094:M 22 May 16:00:39.405 * Background saving terminated with success
31094:M 22 May 16:00:39.434 * Synchronization with slave 10.189.234.152:10007 succeeded
31094:M 22 May 16:00:43.739 # Connection with slave 10.189.234.152:10007 lost.
```

---

**目的端 Redis**
版本：自建 redis6.2.10 集群，3主6从。
日志：在sync-rdb之前程序崩溃，无该时间段的日志

```
204171:M 26 Apr 2023 10:18:04.512 * Starting BGSAVE for SYNC with target: disk
204171:M 26 Apr 2023 10:18:04.512 * Background saving started by pid 205750
205750:C 26 Apr 2023 10:18:04.513 * DB saved on disk
205750:C 26 Apr 2023 10:18:04.513 * RDB: 0 MB of memory used by copy-on-write
204171:M 26 Apr 2023 10:18:04.531 * Background saving terminated with success
204171:M 26 Apr 2023 10:18:04.531 * Synchronization with replica 10.189.60.43:8230 succeeded
204171:M 26 Apr 2023 10:18:06.465 # Cluster state changed: ok
204171:M 26 Apr 2023 10:18:08.617 # CONFIG REWRITE executed with success.
```

**Comment by suxb201** [comment]
集群版不支持 select db，集群版的 Redis 只有 db0。

**Comment by Knomori** [comment]
我们这边源redis单点其实也只是使用了db0。看发布记录scan模式在3.1.9修复了对集群使用select的问题，如果sync模式也能支持就太好啦。我们这边已经使用别的方式同步数据到集群了，非常感谢～

**Comment by suxb201** [comment]
1. 好的，现在 scan 模式应该是没问题的。此外，看你描述是“源为单机redis，默认database:16”。
2. 请问你后来是通过什么方式同步的？

**Comment by Knomori** [comment]
1、源为单机redis4，默认database配置是16，只使用默认的db0，其余数据库无数据。业务无select语句。
2、我们该redis允许停机，使用restore模式进行同步。

**Comment by suxb201** [comment]
明白了，谢谢。

**Comment by suedevops** [comment]
把select 、script都过滤掉还是不行

**Comment by suxb201** [comment]
@suedevops 现在应该没问题了。需要确保源端只使用 db0。
