### ISSUE TITLE
redis 5.0 同步异常 panic: redisWriter received error

### ISSUE THREAD

**Issue by jusl-song** [aliyun/redis-shake#615]
**问题描述**

启动redis-shake执行同步到目标集群会有以下报错，配置中是以源集群的从节点为同步源

源集群主从集群运行正常没有异常日志 

redis-shake 的日志：
```
AOFReader open file. aof_filename=[13810946554804.aof]
goroutine 5 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc00228cf78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001a89c0)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  [

PNC redisWriter received error. error=[ERR The ID specified in XADD is equal or smaller than the target stream top item], argv=[XCLAIM connect_stream congroup zo_zz56_4 0 1685070871482-0 TIME 1685070871482 RETRYCOUNT 1 FORCE JUSTID], slots=[5609], reply=[<nil>]
panic: redisWriter received error. error=[ERR The ID specified in XADD is equal or smaller than the target stream top item], argv=[XCLAIM connect_stream congroup zo_zz56_4 0 1685070871482-0 TIME 1685070871482 RETRYCOUNT 1 FORCE JUSTID], slots=[5609], reply=[<nil>]
```

---

**源端 Redis**
版本：redis5.0 自建 1主2从 3sentinel集群
日志：
```
日志贴在这里
```

---

**目的端 Redis**
版本：redis5.0 自建  1主2从 3sentinel集群
日志：
```
日志贴在这里
```

**Comment by suxb201** [comment]
1. 目的端是不是空的？
2. 是一对一的导入吗，还是二对一？

**Comment by jusl-song** [comment]
目标端是空的
重复尝试的时候也会flushall清空目标集群

一对一导入（源集群从节点 > 目标集群主节点）

**Comment by suxb201** [comment]
1. 源端几个 db？
2. 增量同步阶段报的错是吗？

**Comment by jusl-song** [comment]
1. 源端只有 db1
2. 是的，增量同步阶段报错

**Comment by suxb201** [comment]
目的端此时只有 Shake 在写吗，会有其他写入吗

**Comment by jusl-song** [comment]
没有其他写入，只有redis-shake同步写入

**Comment by suxb201** [comment]
暂时想不出原因。你可以先重试下。

**Comment by jusl-song** [comment]
我将同步源改为 源集群主节点,目标集群执行了flushall之后重新尝试了下，以下报错
```
2023-05-26 11:53:04 INF goroutine 3 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc000189f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001a69c0)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  [
2023-05-26 11:53:04 PNC redisWriter received error. error=[ERR The ID specified in XADD is equal or smaller than the target stream top item], argv=[xadd connect_stream 1684912423503-0 inner_msg {"TypeTag":0,"Data1":{"xxx"},"Data2":null}], slots=[5609], reply=[<nil>]
panic: redisWriter received error. error=[ERR The ID specified in XADD is equal or smaller than the target stream top item], argv=[xadd connect_stream 1684912423503-0 inner_msg {"TypeTag":0,"Data1":{"xxx"},"Data2":null}], slots=[5609], reply=[<nil>]
```

**Comment by jusl-song** [comment]
有一个现象，同步源为源集群主节点进行同步

1、全量同步后，源节点和目标节点的key数量并不接近，可能有过期的原因？
源：
db1:keys=253,expires=250,avg_ttl=136439
目标：
db1:keys=20,expires=20,avg_ttl=83312

2、增量同步panic之后，目标节点突然多出很多key(确认没有其他写入，key会全部过期后为0)
源：
db1:keys=263,expires=260,avg_ttl=145104

目标：
db1:keys=3044,expires=3043,avg_ttl=298120

**Comment by jusl-song** [comment]
又重新尝试了下同步源为 源集群从节点的同步

这算是全量同步阶段失败？  去看了下目标节点的key，key确实已经过去了，不确认是否完整，两遍值是接近的（因为有过期和消费）

```
2023-05-26 12:22:38 INF create dump.rdb file. filename_path=[dump.rdb]
2023-05-26 12:22:38 INF save RDB finished. address=[xxx:6379], total_bytes=[13169]
2023-05-26 12:22:38 INF start send RDB. address=[xxx:6379]
2023-05-26 12:22:38 INF RDB version: 9
2023-05-26 12:22:38 INF RDB AUX fields. key=[redis-ver], value=[4.9.105]
2023-05-26 12:22:38 INF RDB AUX fields. key=[redis-bits], value=[64]
2023-05-26 12:22:38 INF RDB AUX fields. key=[ctime], value=[1685074958]
2023-05-26 12:22:38 INF start save AOF. address=[xxx:6379]
2023-05-26 12:22:38 INF RDB AUX fields. key=[used-mem], value=[2933160]
2023-05-26 12:22:38 INF AOFWriter open file. filename=[13811705609206.aof]
2023-05-26 12:22:38 INF RDB repl-stream-db: 1
2023-05-26 12:22:38 INF RDB AUX fields. key=[repl-id], value=[e0c95d8264072ba50742f2847f81a62deec870e3]
2023-05-26 12:22:38 INF RDB AUX fields. key=[repl-offset], value=[13811705609206]
2023-05-26 12:22:38 INF RDB AUX fields. key=[aof-preamble], value=[0]
2023-05-26 12:22:38 INF RDB resize db. db_size=[353], expire_size=[350]
2023-05-26 12:22:38 INF send RDB finished. address=[xxx:6379], repl-stream-db=[1]
2023-05-26 12:22:39 INF AOFReader open file. aof_filename=[13811705609206.aof]
2023-05-26 12:22:41 INF goroutine 19 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc0000bcf78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0000d09c0)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  [
2023-05-26 12:22:41 PNC redisWriter received error. error=[ERR The ID specified in XADD is equal or smaller than the target stream top item], argv=[xadd connect_stream maxlen ~
```

**Comment by suxb201** [comment]
@jusl-song 确实不对，既然数量不多，可以 keys* 列出 key 后对比下差在哪里。

**Comment by jusl-song** [comment]
看上去也就顺序不一致，其他没什么

**Comment by suxb201** [comment]
> db1:keys=263,expires=260,avg_ttl=145104
> 
> 目标：
> db1:keys=3044,expires=3043,avg_ttl=298120

数量不一样的，可以看看是多了哪些。

**Comment by yaowenhui2019** [comment]
@suxb201 这是redis5.0 stream数据结构的限制https://blog.csdn.net/qq_45776114/article/details/129659085，我猜测会不会是因为redisshake同步redis5.0的stream数据结构的时候没有严格按照它的key的大小xadd导致失败了

**Comment by yaowenhui2019** [comment]
@suxb201 ，https://blog.csdn.net/qq_45776114/article/details/129659085，[我猜测会不会是因为redisshake同步redis5.0的stream数据结构的时候没有严格按照它的key的大小xadd导致失败了]，大佬帮忙确认下～

**Comment by suxb201** [comment]
@yaowenhui2019 这个还需要再测一下确认下，我之前测试是没问题的。

**Comment by baronwangr** [comment]
一般stream出现大概率是因为多个导入器，或者目的端有写入
