### ISSUE TITLE
write: connection reset by peer

### ISSUE THREAD

**Issue by thor533** [aliyun/redis-shake#624]
- [ ] 请确保已经看过 wiki：https://github.com/alibaba/RedisShake/wiki
- [ ] 请确保已经学习过 Markdown 语法，良好的排版有助于维护人员了解你的问题
- [ ] 请在此提供足够的信息供社区维护人员排查问题
- [ ] 请在提交 issue 前删除此模板中多余的文字，包括这几句话

**问题描述**
我用redis-shake进行redis-cluster之间的实时同步，一开始运行实例没有什么问题 正常同步，过了一会，实例进程就挂掉了
这里描述你的问题。

redis-shake 的日志：
```
{"level":"info","time":"2023-06-14T15:45:05+08:00","message":"syncing aof. allowOps=[13.80], disallowOps=[0.00], entryId=[10120], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[34609], aofReceivedOffset=[534081377], aofAppliedOffset=[534046768]"}
{"level":"info","time":"2023-06-14T15:45:10+08:00","message":"syncing aof. allowOps=[23.60], disallowOps=[0.00], entryId=[10238], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[24451], aofReceivedOffset=[535015265], aofAppliedOffset=[534990814]"}
{"level":"info","time":"2023-06-14T15:45:15+08:00","message":"syncing aof. allowOps=[12.60], disallowOps=[0.00], entryId=[10301], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[57241], aofReceivedOffset=[535441249], aofAppliedOffset=[535384008]"}
{"level":"info","time":"2023-06-14T15:45:20+08:00","message":"syncing aof. allowOps=[26.40], disallowOps=[0.00], entryId=[10433], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[19339], aofReceivedOffset=[536211297], aofAppliedOffset=[536191958]"}
{"level":"info","time":"2023-06-14T15:45:25+08:00","message":"syncing aof. allowOps=[15.00], disallowOps=[0.00], entryId=[10508], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[21917], aofReceivedOffset=[537112417], aofAppliedOffset=[537090500]"}
{"level":"info","time":"2023-06-14T15:45:30+08:00","message":"syncing aof. allowOps=[28.20], disallowOps=[0.00], entryId=[10649], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[62381], aofReceivedOffset=[538013537], aofAppliedOffset=[537951156]"}
{"level":"info","time":"2023-06-14T15:45:35+08:00","message":"syncing aof. allowOps=[23.60], disallowOps=[0.00], entryId=[10767], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[12288], aofReceivedOffset=[538865505], aofAppliedOffset=[538853217]"}
{"level":"info","time":"2023-06-14T15:45:40+08:00","message":"syncing aof. allowOps=[25.60], disallowOps=[0.00], entryId=[10895], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[4081], aofReceivedOffset=[539471713], aofAppliedOffset=[539467632]"}
{"level":"info","time":"2023-06-14T15:45:45+08:00","message":"syncing aof. allowOps=[34.20], disallowOps=[0.00], entryId=[11066], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[3548], aofReceivedOffset=[540143457], aofAppliedOffset=[540139909]"}
{"level":"info","time":"2023-06-14T15:45:48+08:00","message":"goroutine 37 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc0000940c0, 0x52}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x816b80, 0xc000059220})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).flush(0xc00005e040)]<-github.com/alibaba/RedisShake/internal/client/redis.go:100 +0x2a  [github.com/alibaba/RedisShake/internal/client.(*Redis).Send(0xc0001d0100, {0xc00230ff88, 0x3, 0x3})]<-github.com/alibaba/RedisShake/internal/client/redis.go:86 +0x7e  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendReplconfAck(0xc0001f4000)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:245 +0xd5  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1]<-github.com/alibaba/RedisShake/internal/reader/psync.go:45 +0x68  ["}
{"level":"panic","time":"2023-06-14T15:45:48+08:00","message":"write tcp 10.210.21.105:58418->10.210.21.105:7002: write: connection reset by peer"}
```

```
shake 的日志贴在这里
```
```
[90m2023-06-14 15:45:40[0m [32mINF[0m syncing aof. allowOps=[25.60], disallowOps=[0.00], entryId=[10895], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[4081], aofReceivedOffset=[539471713], aofAppliedOffset=[539467632]
[90m2023-06-14 15:45:45[0m [32mINF[0m syncing aof. allowOps=[34.20], disallowOps=[0.00], entryId=[11066], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[3548], aofReceivedOffset=[540143457], aofAppliedOffset=[540139909]
[90m2023-06-14 15:45:48[0m [32mINF[0m goroutine 37 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc0000940c0, 0x52}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x816b80, 0xc000059220})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).flush(0xc00005e040)]<-github.com/alibaba/RedisShake/internal/client/redis.go:100 +0x2a  [github.com/alibaba/RedisShake/internal/client.(*Redis).Send(0xc0001d0100, {0xc00230ff88, 0x3, 0x3})]<-github.com/alibaba/RedisShake/internal/client/redis.go:86 +0x7e  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendReplconfAck(0xc0001f4000)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:245 +0xd5  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1]<-github.com/alibaba/RedisShake/internal/reader/psync.go:45 +0x68  [
[90m2023-06-14 15:45:48[0m [1m[31mPNC[0m[0m write tcp 10.210.21.105:58418->10.210.21.105:7002: write: connection reset by peer
panic: write tcp 10.210.21.105:58418->10.210.21.105:7002: write: connection reset by peer

goroutine 37 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000094120, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc00004eae0, {0xc000094120, 0x52})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc00004eae0, {0xc0000940c0, 0x3f1}, {0x0, 0x79a446, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc0000940c0, 0x52}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x816b80, 0xc000059220})
	github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).flush(0xc00005e040)
	github.com/alibaba/RedisShake/internal/client/redis.go:100 +0x2a
github.com/alibaba/RedisShake/internal/client.(*Redis).Send(0xc0001d0100, {0xc00230ff88, 0x3, 0x3})
	github.com/alibaba/RedisShake/internal/client/redis.go:86 +0x7e
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendReplconfAck(0xc0001f4000)
	github.com/alibaba/RedisShake/internal/reader/psync.go:245 +0xd5
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1
	github.com/alibaba/RedisShake/internal/reader/psync.go:45 +0x68

```

---

**源端 Redis**
版本：5.0.8，自建还是云厂商？
日志：
```
日志贴在这里
```

---

**目的端 Redis**
版本：5.0.8，是否是集群？ 是  自建还是云厂商？
日志：
```
日志贴在这里
```

**Comment by thor533** [comment]
the redis-shake version is 3.1.11

**Comment by githubxubin** [comment]
@suxb201

**Comment by thor533** [comment]
@suxb201

**Comment by suxb201** [comment]
请按照 issue 模板给出更多信息
