### ISSUE TITLE
DEL指令报redisWriter received error. error=[EOF]

### ISSUE THREAD

**Issue by l36t** [aliyun/redis-shake#629]
**问题描述**
同步数据时，对于DEL指令报错，reply=[<nil>]，谢谢
redis-shake 的日志：
2023-06-29 16:19:00 INF goroutine 17 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0x7b2730, 0x45}, {0xc000070f78, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc0001a5600)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c  [
2023-06-29 16:19:00 PNC redisWriter received error. error=[EOF], argv=[DEL d0815ee2165991f1dcc5f65e106bc746], slots=[10556], reply=[<nil>]
**源端 Redis**
版本：redis5.0 集群
**目的端 Redis**
predixy 代理tendis集群

**Comment by suxb201** [comment]
目的端的问题，怀疑是 predixy 断开连接了，检查下 predixy 日志吧
