### ISSUE TITLE
anic: redisWriter received error. error=[ERR DUMP payload version or checksum are wrong]

### ISSUE THREAD

**Issue by hidao** [aliyun/redis-shake#639]
**问题描述**

使用 aws elasticCache迁出数据到自建的redis集群报错，提示 anic: redisWriter received error. error=[ERR DUMP payload version or checksum are wrong]

redis-shake 的日志：
```
panic: redisWriter received error. error=[ERR DUMP payload version or checksum are wrong], argv=[RESTORE FSM:terminal:heartbeat:vsim:srg221170gbxtyse 174537  Á{"@class":"com.xx.fsm.domain.TerminalHeartbeat","sn /srg221170gbxtyse  hÀ#Date":1690189908039,"battery 00l`ꈣpuTemper ü r 8375A¡Ś40@A±@À ø2.4GHZ 쀓 CÀU!.@»ImeA
86476604019893Ao@ 358981877349984 I5g¢¢ À[0} ҌªӠ{], slots=[4136], reply=[<nil>]

goroutine 8 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc0002ec000, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0000a8e40, {0xc0002ec000, 0x2b3})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc0000a8e40, {0x7b757c, 0x21c}, {0xc0002e9f78, 0x79f1e6, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0x7b757c, 0x45}, {0xc0002e9f78, 0x4, 0x4})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0xc000060200)
	github.com/alibaba/RedisShake/internal/writer/redis.go:75 +0x3bd
created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter
	github.com/alibaba/RedisShake/internal/writer/redis.go:35 +0x19c
```

---

**源端 Redis**
版本：3.0（aws elasticCache)

**目的端 Redis**
版本：3.0（自建集群）

**Comment by hidao** [comment]
使用 `scan` 模式

**Comment by suxb201** [comment]
1. 怀疑是 EC 的版本问题，你将目的端 Redis 先换成 7.0 试试能行吗
2. 确认下 `FSM:terminal:heartbeat:vsim:srg221170gbxtyse` 是什么类型的数据

**Comment by hidao** [comment]
> 1. 怀疑是 EC 的版本问题，你将目的端 Redis 先换成 7.0 试试能行吗
> 2. 确认下 `FSM:terminal:heartbeat:vsim:srg221170gbxtyse` 是什么类型的数据

第1点待会试试，不过我们的目标是同版本迁移，aws elasticCache这个月要强制升级到4.0，但老项目不敢随便动，第2点，都是jackson 序列化为 String 类型的

**Comment by suxb201** [comment]
建议试试 1，我怀疑 EC 虽然给你显示的是 3.0，但是后面真实引擎版本可能较高。

**Comment by hidao** [comment]
> 建议试试 1，我怀疑 EC 虽然给你显示的是 3.0，但是后面真实引擎版本可能较高。

试了下，目标端用7.0没问题，看了下，`EC` 界面显示引擎版本为 3.2.10 。。。

**Comment by hidao** [comment]
补充一下，target设置为单机不报错，设置type为集群会报错

**Comment by suxb201** [comment]
不一样的报错吧
