### ISSUE TITLE
PNC ERR unknown command 'REPLCONF'

### ISSUE THREAD

**Issue by szy345** [aliyun/redis-shake#658]
**问题描述**
 
源端是阿里云的redis cluster 6.0.14，proxy模式，后端是自己自建的redis cluster 6.0.9
sync 模式同步报错，./redis-shake sync.toml filters/aliyun.lua

more filters/aliyun.lua
-- Aliyun Redis 4.0: skip OPINFO command
function filter(id, is_base, group, cmd_name, keys, slots, db_id, timestamp_ms)
    if cmd_name == "replconf" then
        return 1, db_id -- disallow
    else
        return 0, db_id -- allow
    end
end

sync.toml 配置：

type = "sync"

[source]
address = "r-2vcken7ha7s5xwq5gg.redis.cn-chengdu.rds.aliyuncs.com:6379"
tls = false

[target]
address = "172.19.21.110:6382"
tls = false

[advanced]
dir = "data"
ncpu = 4
pprof_port = 0
metrics_port = 0
log_file = "redis-shake.log"
pipeline_count_limit = 1024
target_redis_client_max_querybuf_len = 1024_000_000
target_redis_proto_max_bulk_len = 512_000_000
redis-shake 的日志：
```
2023-08-24 22:10:31 INF GOOS: linux, GOARCH: amd64
2023-08-24 22:10:31 INF Ncpu: 4, GOMAXPROCS: 4
2023-08-24 22:10:31 INF pid: 298879
2023-08-24 22:10:31 INF pprof_port: 0
2023-08-24 22:10:31 INF no password. address=[172.19.21.110:6382]
2023-08-24 22:10:31 INF redisWriter connected to redis successful. address=[172.19.21.110:6382]
2023-08-24 22:10:31 INF no password. address=[r-2vcken7ha7s5xwq5gg.redis.cn-chengdu.rds.aliyuncs.com:6379]
2023-08-24 22:10:31 INF psyncReader connected to redis successful. address=[r-2vcken7ha7s5xwq5gg.redis.cn-chengdu.rds.aliyuncs.com:6379]
2023-08-24 22:10:31 INF start save RDB. address=[r-2vcken7ha7s5xwq5gg.redis.cn-chengdu.rds.aliyuncs.com:6379]
2023-08-24 22:10:31 INF send [replconf listening-port 10007]
2023-08-24 22:10:31 INF goroutine 17 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc000218000, 0x1e}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x817300, 0xc00021a000})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc000022ba0, {0xc0001a2ff0, 0xc000043f68, 0x1})]<-github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc00005c780)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()]<-github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x72  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead]<-github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f  [
2023-08-24 22:10:31 PNC ERR unknown command 'REPLCONF'
panic: ERR unknown command 'REPLCONF'

goroutine 17 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000218060, 0x0})
        github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0002100c0, {0xc000218060, 0x1e})
        github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc0002100c0, {0xc000218000, 0x3fc}, {0x0, 0x79a446, 0x3})
        github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc000218000, 0x1e}, {0x0, 0x0, 0x0})
        github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x817300, 0xc00021a000})
        github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.(*Redis).DoWithStringReply(0xc000022ba0, {0xc0001a2ff0, 0xc000043f68, 0x1})
        github.com/alibaba/RedisShake/internal/client/redis.go:71 +0x50
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).saveRDB(0xc00005c780)
        github.com/alibaba/RedisShake/internal/reader/psync.go:78 +0x13d
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
        github.com/alibaba/RedisShake/internal/reader/psync.go:46 +0x72
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
        github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f
```

**Comment by suxb201** [comment]
需要开通有复制权限的账号：https://help.aliyun.com/zh/redis/user-guide/create-and-manage-database-accounts

**Comment by szy345** [comment]
![image](https://github.com/tair-opensource/RedisShake/assets/14071421/469b0aba-926e-4f5c-81ca-6b37c3405212)

阿里云的集群版，不支持添加复制账号呢，还是我操作的不对。

**Comment by szy345** [comment]
> 需要开通有复制权限的账号：https://help.aliyun.com/zh/redis/user-guide/create-and-manage-database-accounts

好像集群版不能添加

**Comment by suxb201** [comment]
两个方案：
1. 转直连模式，然后创建复制账号
2. 使用 scan 模式
