### ISSUE TITLE
 同步aof报错

### ISSUE THREAD

**Issue by dba3306** [aliyun/redis-shake#708]
### 问题描述（Issue Description）

每次同步aof的时候会报错

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：3.1.11
- Redis 源端版本（Redis Source Version）：7.0.9
- Redis 目的端版本（Redis Destination Version）：7.0.9
- Redis 部署方式（standalone/cluster/sentinel）: cluster
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：否

### 日志信息（Logs）
```
2023-11-13 15:29:40 INF syncing rdb. percent=[88.99]%, allowOps=[139363.80], disallowOps=[0.00], entryId=[10183574], InQueueEntriesCount=[0], unansweredBytesCount=[15247]bytes, rdbFileSize=[1.332]G, rdbSendSize=[1.186]G
2023-11-13 15:29:45 INF syncing rdb. percent=[95.04]%, allowOps=[137569.59], disallowOps=[0.00], entryId=[10871476], InQueueEntriesCount=[13], unansweredBytesCount=[105152]bytes, rdbFileSize=[1.332]G, rdbSendSize=[1.266]G
2023-11-13 15:29:49 INF send RDB finished. address=[10.52.24.37:6380], repl-stream-db=[0]
2023-11-13 15:29:50 INF AOFReader open file. aof_filename=[191995229118.aof]
2023-11-13 15:29:50 INF syncing aof. allowOps=[102763.00], disallowOps=[0.00], entryId=[11385328], InQueueEntriesCount=[0], unansweredBytesCount=[0]bytes, diff=[6277604], aofReceivedOffset=[192001625494], aofAppliedOffset=[191995347890]
2023-11-13 15:29:54 INF goroutine 9 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x65  [github.com/alibaba/RedisShake/internal/log.Panicf({0xc0005181c0, 0x1a5}, {0x0, 0x0, 0x0})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x36  [github.com/alibaba/RedisShake/internal/log.PanicError({0x816800, 0xc000509cb0})]<-github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33  [github.com/alibaba/RedisShake/internal/client.ArrayString({0x0, 0x0}, {0x816800, 0xc000509cb0})]<-github.com/alibaba/RedisShake/internal/client/reply.go:7 +0x46  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendAOF(0xc000140050, 0xc000122020)]<-github.com/alibaba/RedisShake/internal/reader/psync.go:223 +0x22f  [github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()]<-github.com/alibaba/RedisShake/internal/reader/psync.go:51 +0x114  [created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead]<-github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f  [
2023-11-13 15:29:54 PNC redis: can't parse "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
2023-11-13 15:29:54 INF AOFReader close file. aof_filename=[191995229118.aof]
panic: redis: can't parse "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"

goroutine 9 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0xc000518380, 0x0})
	github.com/rs/zerolog@v1.28.0/log.go:375 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc0007084e0, {0xc000518380, 0x1a5})
	github.com/rs/zerolog@v1.28.0/event.go:156 +0x2b8
github.com/rs/zerolog.(*Event).Msgf(0xc0007084e0, {0xc0005181c0, 0x3f1}, {0x0, 0x79a446, 0x3})
	github.com/rs/zerolog@v1.28.0/event.go:129 +0x4e
github.com/alibaba/RedisShake/internal/log.Panicf({0xc0005181c0, 0x1a5}, {0x0, 0x0, 0x0})
	github.com/alibaba/RedisShake/internal/log/func.go:32 +0xef
github.com/alibaba/RedisShake/internal/log.PanicError({0x816800, 0xc000509cb0})
	github.com/alibaba/RedisShake/internal/log/func.go:36 +0x33
github.com/alibaba/RedisShake/internal/client.ArrayString({0x0, 0x0}, {0x816800, 0xc000509cb0})
	github.com/alibaba/RedisShake/internal/client/reply.go:7 +0x46
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).sendAOF(0xc000140050, 0xc000122020)
	github.com/alibaba/RedisShake/internal/reader/psync.go:223 +0x22f
github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead.func1()
	github.com/alibaba/RedisShake/internal/reader/psync.go:51 +0x114
created by github.com/alibaba/RedisShake/internal/reader.(*psyncReader).StartRead
	github.com/alibaba/RedisShake/internal/reader/psync.go:43 +0x8f
```
大佬们有没有遇到过这种问题？

**Comment by suxb201** [comment]
稳定复现吗 😂
下次遇到可以发一下 191995229118.aof 这个文件吗？
