### ISSUE TITLE
panic: runtime error: makeslice: len out of range when parsing RDB file

### ISSUE THREAD

**Issue by yangtingting-ola** [aliyun/redis-shake#716]
### 问题描述（Issue Description）

在启动redis-shake之后crash, 报panic: runtime error: makeslice: len out of range. 

代码中的readEncodedLength的实现和[RDB length encoding的spec](https://rdb.fnordig.de/file_format.html#length-encoding)不符合， 导致拿到一个很大的length， 超出makeslice的最大可以allocate的长度。  

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：redis-shake-v4.0.2
- Redis 源端版本（Redis Source Version）：6.2.4
- Redis 目的端版本（Redis Destination Version）：6.0.16
- Redis 部署方式（standalone/cluster/sentinel）： 源和目标均为standalone 
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：部署在阿里云ecs实例上

### 日志信息（Logs）

```

2023-11-29 18:29:36 INF load config from file: shake.toml
2023-11-29 18:29:36 INF log_level: [debug], log_file: [/home/ecs-user/tingting.yang/data/shake.log]
2023-11-29 18:29:36 INF changed work dir to [/home/ecs-user/tingting.yang/data]
2023-11-29 18:29:36 INF GOMAXPROCS defaults to the value of runtime.NumCPU [2]
2023-11-29 18:29:36 INF not set pprof port
2023-11-29 18:29:36 INF no function script
2023-11-29 18:29:36 DBG CreateEmptyDir: dir=[/home/ecs-user/tingting.yang/data/reader_172.16.0.32_6379]
2023-11-29 18:29:36 INF create SyncStandaloneReader: 172.16.0.32:6379
2023-11-29 18:29:36 INF create RedisStandaloneWriter: 10.8.10.94:6379
2023-11-29 18:29:36 INF not set status port
2023-11-29 18:29:36 INF start syncing...
2023-11-29 18:29:36 DBG enter StartRead
2023-11-29 18:29:36 DBG sendReplconfListenPort done
2023-11-29 18:29:36 DBG sendPSync done
2023-11-29 18:29:36 DBG [reader_172.16.0.32_6379] source db is doing bgsave.
2023-11-29 18:29:41 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:29:46 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:29:51 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:29:56 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:01 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:06 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:11 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:16 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:21 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:26 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:31 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], waiting bgsave
2023-11-29 18:30:32 DBG [reader_172.16.0.32_6379] source db bgsave finished. timeUsed=[55.49]s
2023-11-29 18:30:32 DBG [reader_172.16.0.32_6379] rdb file size: [2.8 GiB]
2023-11-29 18:30:32 DBG [reader_172.16.0.32_6379] start receiving RDB. path=[/home/ecs-user/tingting.yang/data/reader_172.16.0.32_6379/dump.rdb]
2023-11-29 18:30:36 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-29 18:30:41 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-29 18:30:46 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-29 18:30:51 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] save RDB finished. timeUsed=[23.00]s
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] start sending RDB to target
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] start receiving aof data, and save to file
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] open file for write. filename=[/home/ecs-user/tingting.yang/data/reader_172.16.0.32_6379/0.aof]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB version: 9
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[redis-ver], value=[6.2.4]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[redis-bits], value=[64]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[ctime], value=[1701253776]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[used-mem], value=[13889376656]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB repl-stream-db: [0]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[repl-id], value=[c8e1c05c4582c23a0251c7be4c94a9bb6abd6235]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[repl-offset], value=[36745179]
2023-11-29 18:30:55 DBG [reader_172.16.0.32_6379] RDB AUX: key=[aof-preamble], value=[0]
panic: runtime error: makeslice: len out of range

goroutine 10 [running]:
RedisShake/internal/rdb/structure.ReadBytes({0x92cba0, 0xc0000643c0}, 0x799959?)
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/rdb/structure/byte.go:14 +0x36
RedisShake/internal/rdb/structure.ReadString({0x92cba0, 0xc0000643c0})
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/rdb/structure/string.go:42 +0x1cf
RedisShake/internal/rdb.(*Loader).parseRDBEntry(0xc00010e1b0, 0xc0000643c0)
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/rdb/rdb.go:156 +0x7c5
RedisShake/internal/rdb.(*Loader).ParseRDB(0xc00010e1b0)
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/rdb/rdb.go:91 +0x470
RedisShake/internal/reader.(*syncStandaloneReader).sendRDB(0xc000164000)
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/reader/sync_standalone_reader.go:251 +0x1ab
RedisShake/internal/reader.(*syncStandaloneReader).StartRead.func1()
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/reader/sync_standalone_reader.go:103 +0x14a
created by RedisShake/internal/reader.(*syncStandaloneReader).StartRead
        /Users/tingting.yang/golang/src/github.com/tair-opensource/RedisShake/internal/reader/sync_standalone_reader.go:93 +0xaa
```

在readEncodedLength加了一点日志： 
```
func readEncodedLength(rd io.Reader) (length uint64, special bool, err error) {
	var lengthBuffer = make([]byte, 8)

	firstByte := ReadByte(rd)
	first2bits := (firstByte & 0xc0) >> 6 // first 2 bits of encoding
	switch first2bits {
	case RDB6ByteLen:
		length = uint64(firstByte) & 0x3f
	case RDB14ByteLen:
		nextByte := ReadByte(rd)
		length = (uint64(firstByte)&0x3f)<<8 | uint64(nextByte)
	case len32or64Bit:
		// if firstByte == RDB32ByteLen {
		_, err = io.ReadFull(rd, lengthBuffer[0:4])
		if err != nil {
			return 0, false, fmt.Errorf("read len32Bit failed: %s", err.Error())
		}
		length = uint64(binary.BigEndian.Uint32(lengthBuffer[0:4]))
		log.Debugf("readEncodedLength: firstByte = %x, first2bits = %x, lengthBuffer = %+v, length = %d", firstByte, first2bits, lengthBuffer[0:4], length)
		// } else if firstByte == RDB64ByteLen {
		// 	_, err = io.ReadFull(rd, lengthBuffer)
		// 	if err != nil {
		// 		return 0, false, fmt.Errorf("read len64Bit failed: %s", err.Error())
		// 	}
		// 	length = binary.BigEndian.Uint64(lengthBuffer)
		// } else {
		// 	return 0, false, fmt.Errorf("illegal length encoding: %x", firstByte)
		// }
	case lenSpecial:
		special = true
		length = uint64(firstByte) & 0x3f
		log.Debugf("readEncodedLength: found one length encoding in soecial format, length = %d", length)
	}
	return length, special, nil
}
```
```
2023-11-30 11:04:04 DBG [reader_172.16.0.32_6379] start receiving RDB. path=[/home/ecs-user/tingting.yang/data/reader_172.16.0.32_6379/dump.rdb]
2023-11-30 11:04:04 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-30 11:04:09 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-30 11:04:14 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-30 11:04:19 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-30 11:04:24 INF read_count=[0], read_ops=[0.00], write_count=[0], write_ops=[0.00], receiving rdb
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] save RDB finished. timeUsed=[22.59]s
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] start sending RDB to target
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] start receiving aof data, and save to file
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] open file for write. filename=[/home/ecs-user/tingting.yang/data/reader_172.16.0.32_6379/0.aof]
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB version: 9
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[redis-ver], value=[6.2.4]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG readEncodedLength: found one length encoding in soecial format, length = 0
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[redis-bits], value=[64]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG readEncodedLength: found one length encoding in soecial format, length = 2
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[ctime], value=[1701313390]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[used-mem], value=[13892992720]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG readEncodedLength: found one length encoding in soecial format, length = 0
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB repl-stream-db: [0]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[repl-id], value=[87810c4906396199762476d4ada85b2b40a06ca0]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG readEncodedLength: found one length encoding in soecial format, length = 2
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[repl-offset], value=[69111857]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 250
2023-11-30 11:04:27 DBG readEncodedLength: found one length encoding in soecial format, length = 0
2023-11-30 11:04:27 DBG [reader_172.16.0.32_6379] RDB AUX: key=[aof-preamble], value=[0]
2023-11-30 11:04:27 DBG parseRBDEntry: typeByte = 247
2023-11-30 11:04:27 DBG readEncodedLength: firstByte = 81, first2bits = 2, lengthBuffer = [177 199 109 202], length = 2982637002
```
### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

```
function = ""


[sync_reader]
cluster = false             # set to true if source is a redis cluster
address = "172.16.0.32:6379"  # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
tls = false
sync_rdb = true # set to false if you don't want to sync rdb
sync_aof = true # set to false if you don't want to sync aof

# [scan_reader]
# cluster = false            # set to true if source is a redis cluster
# address = "127.0.0.1:6379" # when cluster is true, set address to one of the cluster node
# username = ""              # keep empty if not using ACL
# password = ""              # keep empty if no authentication is required
# ksn = false                # set to true to enabled Redis keyspace notifications (KSN) subscription
# tls = false

# [rdb_reader]
# filepath = "/tmp/dump.rdb"

[redis_writer]
cluster = false            # set to true if target is a redis cluster
address = "10.8.10.94:6379" # when cluster is true, set address to one of the cluster node
username = ""              # keep empty if not using ACL
password = ""              # keep empty if no authentication is required
tls = false


[advanced]
dir = "data"
ncpu = 0        # runtime.GOMAXPROCS, 0 means use runtime.NumCPU() cpu cores
pprof_port = 0  # pprof port, 0 means disable
status_port = 0 # status port, 0 means disable

# log
log_file = "shake.log"
log_level = "debug"     # debug, info or warn
log_interval = 5       # in seconds

# redis-shake gets key and value from rdb file, and uses RESTORE command to
# create the key in target redis. Redis RESTORE will return a "Target key name
# is busy" error when key already exists. You can use this configuration item
# to change the default behavior of restore:
# panic:   redis-shake will stop when meet "Target key name is busy" error.
# rewrite: redis-shake will replace the key with new value.
# ignore:  redis-shake will skip restore the key when meet "Target key name is busy" error.
rdb_restore_command_behavior = "panic" # panic, rewrite or skip

# redis-shake uses pipeline to improve sending performance.
# This item limits the maximum number of commands in a pipeline.
pipeline_count_limit = 1024

# Client query buffers accumulate new commands. They are limited to a fixed
# amount by default. This amount is normally 1gb.
target_redis_client_max_querybuf_len = 1024_000_000

# In the Redis protocol, bulk requests, that are, elements representing single
# strings, are normally limited to 512 mb.
target_redis_proto_max_bulk_len = 512_000_000

# If the source is Elasticache or MemoryDB, you can set this item.
aws_psync = "" # example: aws_psync = "10.0.0.1:6379@nmfu2sl5osync,10.0.0.1:6379@xhma21xfkssync"

[module]
# The data format for BF.LOADCHUNK is not compatible in different versions. v2.6.3 <=> 20603
target_mbbloom_version = 20603
```

Please provide any additional information, such as configuration files, error messages, or screenshots.

**Comment by suxb201** [comment]
检查了一下，感觉我写的没有错误。你给的引用文档可能较老，没有 64 byte 的数值类型，参考 Redis 的代码：
```c
int rdbLoadLenByRef(rio *rdb, int *isencoded, uint64_t *lenptr) {
    unsigned char buf[2];
    int type;

    if (isencoded) *isencoded = 0;
    if (rioRead(rdb,buf,1) == 0) return -1;
    type = (buf[0]&0xC0)>>6;
    if (type == RDB_ENCVAL) {
        /* Read a 6 bit encoding type. */
        if (isencoded) *isencoded = 1;
        *lenptr = buf[0]&0x3F;
    } else if (type == RDB_6BITLEN) {
        /* Read a 6 bit len. */
        *lenptr = buf[0]&0x3F;
    } else if (type == RDB_14BITLEN) {
        /* Read a 14 bit len. */
        if (rioRead(rdb,buf+1,1) == 0) return -1;
        *lenptr = ((buf[0]&0x3F)<<8)|buf[1];
    } else if (buf[0] == RDB_32BITLEN) {
        /* Read a 32 bit len. */
        uint32_t len;
        if (rioRead(rdb,&len,4) == 0) return -1;
        *lenptr = ntohl(len);
    } else if (buf[0] == RDB_64BITLEN) {
        /* Read a 64 bit len. */
        uint64_t len;
        if (rioRead(rdb,&len,8) == 0) return -1;
        *lenptr = ntohu64(len);
    } else {
        rdbReportCorruptRDB(
            "Unknown length encoding %d in rdbLoadLen()",type);
        return -1; /* Never reached. */
    }
    return 0;
}
```

看你的 debug 信息，firstByte = %x 输出为 81，转为 10 进制则为 129，属于 RDB_64BITLEN，应该就是一个大数。

目前怀疑，是你的 RDB 中确实存在一个大 lenght，但是 shake 某些 buffer 大小不够导致错误。
方便的话发我 dump.rdb 文件分析一下。

**Comment by yangtingting-ola** [comment]
已找到原因， 源端有使用redissearch module, 现在RedisShake不支持RedisSearch的RDB解码
