### ISSUE TITLE
rdb文件导入过程中，日志打印堆栈退出，数据迁移失败

### ISSUE THREAD

**Issue by CappuccinoAaron** [aliyun/redis-shake#848]
### 问题描述（Issue Description）

rdb文件导入过程中，日志打印堆栈退出，数据迁移失败

### 环境信息（Environment）

- RedisShake 版本（RedisShake Version）：v3.1.11  
- Redis 源端版本（Redis Source Version）：RDB文件
- Redis 目的端版本（Redis Destination Version）：4.0
- Redis 部署方式（standalone/cluster/sentinel）：**standalone**
- 是否在云服务商实例上部署（Deployed on Cloud Provider）：是，小程序云

### 日志信息（Logs）

如果有错误日志或其他相关日志，请在这里提供。

2024-08-01 16:40:01 INF send RDB finished. path=[/Users/linsheng/Downloads/dump/dump.rdb]
2024-08-01 16:40:01 INF goroutine 19 [running]:  [runtime/debug.Stack()]<-runtime/debug/stack.go:24 +0x88  [github.com/alibaba/RedisShake/internal/log.Panicf({0x1006d9bec, 0x45}, {0x14000097f88, 0x4, 0x4})]<-github.com/alibaba/RedisShake/internal/log/func.go:27 +0x20  [github.com/alibaba/RedisShake/internal/writer.(*redisWriter).flushInterval(0x14000032a00)]<-github.com/alibaba/RedisShake/internal/writer/redis.go:80 +0x394  [created by github.com/alibaba/RedisShake/internal/writer.NewRedisWriter]<-github.com/alibaba/RedisShake/internal/writer/redis.go:36 +0x1ac  [
fn�4-08-oanojcnoxi $isnod (co ncx`@j #jo .ain $ sd sjodj��]ߊ�x� replace], slots=[3769], reply=[<nil>]ore code 0 �@Z@kansodunaoufnoau 

### 其他信息（Additional Information）

请提供任何其他相关的信息，如配置文件、错误信息或截图等。

**Comment by suxb201** [comment]
试试新版本。

**Comment by CappuccinoAaron** [comment]
目前我们所在的官方脚本使用的是3.x版本，升级到4.x需要很长的排期～
之前描述有一些错误，我们是standalone方式导入，看起来日志是一个info级别的，但是不知道为啥数据导入直接失败了，这块能帮忙中断的具体原因嘛～

**Comment by suxb201** [comment]
你这日志后面为什么有 `ore code 0 �@z@kansodunaoufnoau`，不完整。感觉是漏复制日志了？

**Comment by CappuccinoAaron** [comment]
![20240801194609](https://github.com/user-attachments/assets/d3406dce-d8cf-478d-9686-cde8c8dcd1bf)
感觉是编码问题，我这边展示的这些都复制进来了

**Comment by suxb201** [comment]
看不出问题原因，RDB 是什么版本的 Redis 产生的？不能比 4.0 高。

**Comment by CappuccinoAaron** [comment]
两个redis版本都是4.0的，rdb数据用rdbtools解析也是正常的
